### ISSUE TITLE
Can't upload app with spaces in the title.

### ISSUE THREAD

**Issue by MLADevelopmentTeam** [microsoft/fastlane-plugin-appcenter#107]
Using version 1.3.0 and an iOS app with spaces in the title results in "URI::InvalidURIError: [!] bad URI(is not URI?)".  I tried changes the spaces to dashes and got "App with name xxx-xxx-xxx not found".

**Comment by evkhramkov** [comment]
Please make sure you're using app name as it appears in browser url

![image](https://user-images.githubusercontent.com/27571887/63446086-6c698c00-c3ee-11e9-855e-59fbeef95e9a.png)

**Comment by MLADevelopmentTeam** [comment]
I did that.  That's why I said in my first comment that I used the App name with dashes.  Figured that would have made it clear.

I took out the app_os: "ios" line which apparently doesn't have the correct value anyway since that lead to a "Select Platform" prompt.  Without that I get "Error getting app blahblahblah-6drc/xxx-xxx-xxx, 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}"

**Comment by jpeg-ms** [comment]
@benkane is correct, the CLI returns the proper name.
I've marked this as enhancement, as it would still be nice to have the option to use a best guess on the "Display Name" rather than the app name.

**Comment by vg-identance** [comment]
Seems there is a similar issue with distribution names with spaces

**Comment by pyby** [comment]
@vg-identance We were able to use its with the same remark that you have to used the app name or group name as it appears in browser url, not as it prompts on the website.

With the 1.5.0 release, it works. `Alpha Testers` is `Alpha-Testers` and distribution groups work as well, with a dash for spaces, to the `%20`.

**Comment by jpeg-ms** [comment]
For group names, they will automatically be URL-encoded so spaces will become `%20`, as appears in the URL on App Center portal. This is valid:
```
destinations: "A group with spaces"
```
This corresponds to `.../distribution-groups/A%20group%20with%20spaces/...`
