### ISSUE TITLE
Fetch devices action – How would you prefer I publish?

### ISSUE THREAD

**Issue by benkane** [microsoft/fastlane-plugin-appcenter#109]
I've created a plugin for fetching a combined list of devices for all distribution groups for an iOS app in App Center (useful when combined with `register_devices` and `match`). Right now I have it locally as a plugin. I was going to publish it as a plugin, but I realized since this plugin is generically named "appcenter", maybe you'd like a PR to add it as an additional action provided by this plugin.

Let me know which you'd prefer – I'm happy to publish the plugin separately or make a PR as an action to be maintained as part of this plugin.

**Comment by benkane** [comment]
Closely related to issue #3

**Comment by bytenik** [comment]
@benkane Did you make your own?

**Comment by benkane** [comment]
@bytenik I did. I’ll try to publish it today. Just need to add some documentation and ideally unit tests

**Comment by bytenik** [comment]
That's fantastic news. I'm finally trying to get off of HockeyApp and this was a big blocker.

**Comment by bytenik** [comment]
Hey, sorry to bug again. Did you have a chance to do this? Thanks!

**Comment by benkane** [comment]
Working on it, sorry for the delay! I will post here when I publish it. If it's not today it will be early next week, I'm actively working on the documentation, but can't dedicate 100% of my time to it

**Comment by jpeg-ms** [comment]
Hi @benkane,
I'm really sorry we didn't check this ticket earlier :( 
I understand you are now working on a separate plugin, but if you eventually decide to send a PR our way, I'd be happy to review it and get it merged.

**Comment by benkane** [comment]
Hi @jpeg-ms, good timing - I was going to publish today :) I have finished unit tests but I'll need to update the documentation now that it'll be under this plugin instead of a separate one. I'll make a PR either today or tomorrow.

cc @bytenik since I know you're waiting for this

**Comment by benkane** [comment]
Added #123

**Comment by benkane** [comment]
Hi @jpeg-ms, I've added the PR for this feature if you want to take a look :)

**Comment by benkane** [comment]
This is now supported, see #123 and #126
