### ISSUE TITLE
Param documentation for `app_name` and example Fastfile disagree

### ISSUE THREAD

**Issue by janpio** [Microsoft/fastlane-plugin-appcenter#11]
Example `Fastfile` and param documentation contradict each other:
https://github.com/Microsoft/fastlane-plugin-appcenter/blob/9f99aab3ee7d9bf971a2f72b59e3e2d5043fce77/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L442
vs. 
https://github.com/Microsoft/fastlane-plugin-appcenter/blob/9f99aab3ee7d9bf971a2f72b59e3e2d5043fce77/fastlane/Fastfile#L10
Or did I miss anything?

**Comment by evkhramkov** [comment]
@janpio prompt skipped in tests, in real usage it will work as documented

https://github.com/Microsoft/fastlane-plugin-appcenter/blob/9f99aab3ee7d9bf971a2f72b59e3e2d5043fce77/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L358
