### ISSUE TITLE
Platform does not match. Expected value: iOS. Actual value: Android

### ISSUE THREAD

**Issue by golanshy** [microsoft/fastlane-plugin-appcenter#111]
I'm trying to upload an Android app to a new Organisation and I get the following error:
{"status"=>"error", "message"=>"Platform does not match. Expected value: iOS. Actual value: Android."}
The organisation has no apps yet and I couldn't find anything in the settings to tell it's an iOS only (We wish it to be both Android & iOS)
Appreciate your help.

appcenter_upload(
            api_token: ENV["APPCENTER_API_TOKEN"],
            owner_name: ownerName,
            owner_type: "organization",
            app_os: 'Android',
            app_platform: 'Java',
            app_name: appName,
            apk: "./outputs/apksV5.x.x/" + filename,
            notify_testers: true
          )

**Comment by golanshy** [comment]
@evkhramkov Sorry, can't see any blue button in right bottom corner, can you send me a link please?

**Comment by golanshy** [comment]
Oh thanks, I'll do that.

**Comment by krimsonkla** [comment]
@golanshy See the comments in this other issue report https://github.com/microsoft/fastlane-plugin-appcenter/issues/28#issuecomment-511053298

**Comment by Bertges** [comment]
I'm facing the same issue: 

> Error uploading binary 422: {"status"=>"error", "message"=>"Platform does not match. Expected value: Android. Actual value: iOS."}

I have two apps in AppCenter, both called "MyApp", but one is for iOS platform and the another one for Android.

This is my appcenter_upload action:

```
appcenter_upload(
      api_token: "token",
      owner_name: "owner",
      app_name: "MyApp",
      app_platform: 'iOS',
      app_os: 'iOS',
      ipa: "./MyApp.ipa",
      notify_testers: false
    )
```

**Comment by evkhramkov** [comment]
@Bertges you need to double check actual name of your app. You can have two apps with the same `display_name` but their names will be unique

E.g. I have two apps named `MyApp` in my test org

![image](https://user-images.githubusercontent.com/27571887/64044609-16969180-cb1c-11e9-9910-ee7652a3cf5a.png)

first iOS app `name` and `display_name` are the same

![image](https://user-images.githubusercontent.com/27571887/64044721-607f7780-cb1c-11e9-9e18-b24af2d7ccf4.png)

for second Android app actual name is `MyApp-1`

<img width="579" alt="Screen Shot 2019-08-30 at 11 50 10 AM" src="https://user-images.githubusercontent.com/27571887/64044761-7b51ec00-cb1c-11e9-9c5a-9d607509bb27.png">

**Comment by Bertges** [comment]
@evkhramkov thank you! That was exactly what I needed.

**Comment by jpeg-ms** [comment]
Hi @golanshy, did the above answer solve your issue?

**Comment by Ajaykn21** [comment]
Closing this as there is no response.
@golanshy Feel free to reach out to us if you are still facing the issue.
