### ISSUE TITLE
Upload build via Fastlane fastfile and getting error and build is not submitted

### ISSUE THREAD

**Issue by mundramanish** [microsoft/fastlane-plugin-appcenter#114]
Hello members,

I'm trying to upload build via Fastlane I added few lines script as mentioned on appcenter document 

   **appcenter_upload(
       api_token: ENV["APPCENTER_API_TOKEN"], 
       owner_name: scheme,
       app_os: "iOS",
       app_platform: "Objective-C-Swift",
       app_name: scheme,
       app_display_name: "Test",
       ipa: "./Build/#{scheme}.ipa",
       destinations: "My Build",
       destination_type: "group",
       notify_testers: true
   )**

But I'm getting an error and build is not uploaded.
Thee error is 

 ## Error getting app APP_NAME, 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}

## Error creating app 409: {"error"=>{"code"=>"Conflict", "message"=>"Validation error"}}

Please help me out and also i tried all types of keys which is explained in document.

Thanks

**Comment by edwardbc** [comment]
Check this thread here https://github.com/microsoft/fastlane-plugin-appcenter/issues/111#issuecomment-526710094 
The `app_name` doesn't really refer to the name of the app on the listing, but the app in the url when you access it.

**Comment by jpeg-ms** [comment]
Hi @mundramanish, did the above answer solve your issue?

**Comment by Ajaykn21** [comment]
Hi @mundramanish, closing as there is no response.
Hopefully the above answer solved your issue.
Feel free to reach out to us if you are still facing.
