### ISSUE TITLE
Could not find action, lane or variable 'appcenter_upload'

### ISSUE THREAD

**Issue by dfiggtns** [microsoft/fastlane-plugin-appcenter#117]
I've tried to install this plugin following the instructions in the readme and I get the following output:

    Plugin 'fastlane-plugin-appcenter' was added to './fastlane/Pluginfile'
    Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
    Installing plugin dependencies...
    Successfully installed plugins

but I get the following error:

    Could not find action, lane or variable 'appcenter_upload'. Check out the documentation for more details: https://docs.fastlane.tools/actions

when I run the following command:

    bundle exec fastlane appcenter

I've checked out the documentation, but there's no mention of appcenter_upload on the page.

My gemfile is:

    source "https://rubygems.org"

    gem "fastlane"
    gem "cocoapods"

    plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
    eval_gemfile(plugins_path) if File.exist?(plugins_path)

My fastfile lane is:

    lane :appcenter do
       appcenter_upload(
        api_token: "????",
        apk: "../path-to-apk/myapp.apk",
        app_name: "MyApp",
        app_os: 'Android',
        owner_name: "MyOwner",
      )
    end

So I have a couple of questions:

1. Is appcenter_upload available in fastlane yet?
2. If it is, why is fastlane not finding the appcenter_upload action?

**Comment by evorotnikov** [comment]
+1 same here

**Comment by aerickson14** [comment]
Double check to make sure your `fastlane` directory is at the same level as your `Gemfile`. If fastlane is actually at a different path you will need to update this line in your Gemfile accordingly:

```plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')```

**Comment by jpeg-ms** [comment]
Hi @dfiggtns , did the above answer by @aerickson14 solve your issue?

**Comment by dfiggtns** [comment]
@aerickson14, thanks for the suggestion, but that line was already in my Gemfile. together with the following line:

    eval_gemfile(plugins_path) if File.exist?(plugins_path)

I don't know whether that makes any difference.

There is no fastlane folder under /src, but there are fastlane folders in /platforms/android and /platforms/ios. Is that the correct location for them or should there be one under /src?

I ask, because the fastfile files in each location are tailored to that platform, so I'm not sure what it should contain, if it needs to be at the /src level.

**Comment by jpeg-ms** [comment]
The configurations for App Center will also need to be tailored for each platform, as apps on App Center only support one platform at a time (they have different names).

I am not sure what is your folder structure, where are your Gemfile and fastlane folders. I would expect one of each for both platforms.

Note: The line `eval_gemfile(plugins_path) if File.exist?(plugins_path)` should be in the Gemfile, this is expected.

**Comment by aerickson14** [comment]
If your fastlane folders are `/platforms/android` and `/platforms/ios` you may need two plugin loading commands in your Gemfile that account for the extra directories:
```
plugins_path = File.join(File.dirname(__FILE__), 'platforms', 'android', 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
plugins_path = File.join(File.dirname(__FILE__), 'platforms', 'ios', 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

or something similar to the above.

**Comment by dfiggtns** [comment]
I've also been getting the error when I run the ios appcenter lane:

    Error uploading binary 422: {"status"=>"error", "message"=>"Platform does not match. Expected value: Android. Actual value: iOS."}

which I can't figure out either. What value should I put in the app_name field? I copied the App Name directly from the App Center. Is that right or is there another value I should use?

**Comment by dfiggtns** [comment]
OK, well I managed figure out the solution.

A bit obscure, because it turns out I was focusing on the wrong area.

The problem was that I was using the wrong app_name, so it didn't match the one that App Center uses. There are 2 app names, one that appears in the App Center UI and one that appears in the url, when you go into the app details (which I'll call the app id, so we don't get confused).

The format of the url is:

    https://appcenter.ms/orgs/{org_name}/apps/{app_id}/

It's the app_id from the url that you need to use in the app_name field of the appcenter_upload parameters. Why they don't show this on the app's settings page in App Center, I don't know, but I think it would make it a lot easier, if they did, rather than having to scrape it from the url.

So my problem turned out to be that App Center had assigned the app_id Quick-Nurse to the android version and Quick-Nurse-1 to the ios version, which is why the plugin was getting confused when it tried to upload the ios version using the android app_id.

I hope that helps anyone coming across a similar problem.

(As an aside, I think it would be a useful enhancement for this plugin to call the app_name parm app_id for the same reason as above).

**Comment by jpeg-ms** [comment]
I have updated the main documentation (README.md) to clarify this problem, as I've seen it happen quite a few times.
It now seems that all your issues are resolved, I will close this ticket for now.
And thanks for using App Center! 🎉
