### ISSUE TITLE
appcenter_upload failing

### ISSUE THREAD

**Issue by nareen2** [microsoft/fastlane-plugin-appcenter#119]
I am using this plugin to upload the builds, but it is failing with:

/Users/$USER/.rvm/gems/ruby-2.6.3/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:6:in `<module:FaradayMiddleware>': [!] uninitialized constant Faraday::Error::ClientError (NameError)
09:51:52 Did you mean?  Faraday::ClientError

**Comment by ethansinjin** [comment]
This was resolved for me when I used `bundle update` to switch from 
faraday (0.16.0)
to
faraday (0.16.2)

**Comment by nareen2** [comment]
I was able to resolve this issue when I pinned the `faraday` gem to '0.15.4' in my Gemfile. @ethansinjin apparently faraday-0.16.2 causing some issues in test-flight uploads. Hopefully, 0.16.3 would resolve all the issues.
