### ISSUE TITLE
How to add special characters to release_notes

### ISSUE THREAD

**Issue by punksta** [microsoft/fastlane-plugin-appcenter#120]
Hello, I want to add line break to release notes. Is it possible?

```
    export APPCENTER_DISTRIBUTE_RELEASE_NOTES="merge request $TITLE\n$URL"
```

it's being added like this:

<img width="695" alt="изображение" src="https://user-images.githubusercontent.com/13404754/65973526-259e9580-e474-11e9-8d79-73de8ab6db84.png">

**Comment by punksta** [comment]
release notes editor in the web portal says "Styling with markdown is supported. 5000 characters or less."

but neither `<br/>` nor `  `(double space) does not work for me.

**Comment by punksta** [comment]
Somehow managed to add new lines using markdown, but it's steal unclear what markdown tags are supported.

**Comment by ppowers10** [comment]
@punksta What markdown ended up working for you?  I'm in the same situation and can't figure out which one's work as expected.

**Comment by Woverlin** [comment]
I still face with this problem, anyone fixed ?

**Comment by MikhailSuendukov** [comment]
Hello @Woverlin, can you please confirm that markdown works for you?

**Comment by maksimdyakonov** [comment]
Double space doesn't work for me
