### ISSUE TITLE
Android Binary not uploading to app center.

### ISSUE THREAD

**Issue by aagarw33** [microsoft/fastlane-plugin-appcenter#122]
Hi,

I have not been able to upload the binary successfully. Every time I try I get
`Error uploading binary 500
.....
Release aborted`

The status.appcenter.ms page show all services are up. Can someone please help?

**Comment by aagarw33** [comment]
My iOS upload worked, what am I missing for Android? the action config is same for both.

**Comment by aagarw33** [comment]
@phillipleblanc 
I tried uploading the binary from App center portal, it does not work over there as well, same error.

![Screen Shot 2019-10-08 at 12 30 01 PM](https://user-images.githubusercontent.com/7662849/66418371-93dcde00-e9c7-11e9-961c-a6b59a736fef.png)

Is form data correct? It says ipa which is for iOS, but I upload apk for Android.

![Screen Shot 2019-10-08 at 12 30 10 PM](https://user-images.githubusercontent.com/7662849/66418440-ba9b1480-e9c7-11e9-8e4b-3d43d7a755c1.png)

**Comment by phillipleblanc** [comment]
@aagarw33 - To better help support you, can you please logon to the App Center portal and click the blue bubble in the bottom right corner? Our support team will be able to collect more information and see what is going on. Thanks!

**Comment by aagarw33** [comment]
@phillipleblanc I don't see any blue bubble in bottom right :(

**Comment by Ajaykn21** [comment]
Hi @aagarw33 
You should be able to see the blue button like in the below screenshot.
<img width="972" alt="image" src="https://user-images.githubusercontent.com/40024974/66547412-2329f300-eb7a-11e9-9f12-9ba918b74610.png">

Also to answer your query, we need to give the format as `ipa` for any kind of package (even for android)
<img width="972" alt="image" src="https://user-images.githubusercontent.com/40024974/66547559-79973180-eb7a-11e9-9dea-cb2e6b65319c.png">

**Comment by aagarw33** [comment]
Hey @Ajaykn21 

Please see the screenshot below. I don't see that button.

![Screen Shot 2019-10-10 at 8 59 57 AM](https://user-images.githubusercontent.com/7662849/66578175-3cae4900-eb40-11e9-9f98-a705ae6c3193.png)

**Comment by aagarw33** [comment]
@Ajaykn21 

Seems like the feedback option is not available in Google Chrome, I am using google chrome canary build. I tried safari and was able to see the feedback button.

I sent message over there.

**Comment by aagarw33** [comment]
iOS fastlane upload is stuck for more than 15 mins
![Screen Shot 2019-10-11 at 4 03 56 PM](https://user-images.githubusercontent.com/7662849/66685131-3b187a00-ec41-11e9-80a3-d0debe39abaf.png)

**Comment by jpeg-ms** [comment]
I think this is not related to the fastlane plugin, and hopefully your issue has been solved by customer support. So I will close this issue for now.
