### ISSUE TITLE
Question: Should a build automatically be distributed after it's uploaded?

### ISSUE THREAD

**Issue by benkane** [microsoft/fastlane-plugin-appcenter#130]
I noticed my webhook to notify Slack of new builds isn't firing after uploading, but if I go to App Center and explicitly distribute the build it does.

Is `appcenter_upload` also supposed to distribute builds?

**Comment by jpeg-ms** [comment]
`appcenter_upload` distributes builds to the specified `destinations` (group or store), which is "Collaborators" group by default [*]. `notify_testers` is by default `false` in our plugin, but you can set it to `true`, and this will send emails to individual testers (it doesn't do anything for stores).

There may be an issue with this `notify_testers` flag handling, which would also disable webhooks, I remember something like this but can't find a reference.

[*] This is why I used "Collaborators" by default in your new feature :)

**Comment by benkane** [comment]
Ahh that could be the issue. HockeyApp had notifying testers on by default. Didn't notice it's off for App Center. I'll try that and see if the webhook is fired along with the emails

**Comment by benkane** [comment]
That worked, thanks! It might be useful to be able to fire that webhook without notifying testers, but that's probably a separate issue.
