### ISSUE TITLE
[Improvement]Display build number to slack message

### ISSUE THREAD

**Issue by nickhung13** [microsoft/fastlane-plugin-appcenter#134]
We moved our project from HockeyApp to App Center. I integrate slack to send message when app was uploaded to App Center.  But it only displays version name without build number. 

<img width="459" alt="hockeyapp" src="https://user-images.githubusercontent.com/20365381/67186884-9144a480-f41b-11e9-892a-0e0a04c5d852.png">

<img width="298" alt="appcenter" src="https://user-images.githubusercontent.com/20365381/67186765-5478ad80-f41b-11e9-9d9b-1a359ac1825a.png">

Can you provide to display the build number? 
Thanks

**Comment by phillipleblanc** [comment]
@nickhung13 This feature would be more appropriate in the main App Center repo. You can file it here: https://github.com/microsoft/appcenter/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=

**Comment by nickhung13** [comment]
Got it, thanks
