### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by adityakhatkhate** [microsoft/fastlane-plugin-appcenter#136]
Hi,

I am using this plugin to upload to appcenter from our fastlane setup and it works great! I am however unable to find a way to upload to Windows since the extensions supported by appcenter are not supported by the plugin. Can you please provide an example of a windows upload to appcenter using the plugin.

```
app_name: <my_app_name>,
app_os: "Windows",
app_platform: "Unity",
file: zip_path
```

Thanks.

**Comment by jpeg-ms** [comment]
Hi @adityakhatkhate,

We don't support Windows with the fastlane plugin. We only support ios, android and macOS, like fastlane itself. You may have a look at the [App Center CLI](/microsoft/appcenter-cli) instead, if you have a need for automation.

I'm going to leave this issue open as a feature request. But out of curiosity, are you using other features of fastlane for Windows/Unity builds?

**Comment by adityakhatkhate** [comment]
Hmm, Fastlane did support windows out of the box when it was being used with hockeyapp. We used to create a zip and upload that using Fastlane’s hockeyapp plugin. However, now we have no option to upload the zip in the appcenter plugin.

Yep, we utilize Fastlane for our internal build and deploy processes.

Best,
Aditya.

**Comment by adityakhatkhate** [comment]
Hmm, Fastlane did support windows out of the box when it was being used with hockeyapp. We used to create a zip and upload that using Fastlane’s hockeyapp plugin. However, now we have no option to upload the zip in the appcenter plugin.

**Comment by jpeg-ms** [comment]
Okay, this is great information. I'll see what we can do.

**Comment by adityakhatkhate** [comment]
Thanks Jean-Philippe. Appreciate you looking into this. Our team has been very excited for this move to appcenter and will really appreciate anything you can do to help us. 

From the initial looks of it, it seems like an extension whitelisting error when i try to pass `app_os` as `windows` and `app_platform` as `unity` - ```Only [".aab", ".app", ".app.zip", ".apk", ".dmg", ".ipa", ".pkg"] formats are allowed, you provided ".zip"```

**Comment by adityakhatkhate** [comment]
Hi @jpeg-ms , wanted to follow up on this one to see if it can be made part of the 2019 roadmap before the cutover from hockeyapp to appcenter. This will help us avoid implement an adaptation of fastlane and appcenter cli across the large number of hockeyapp rinks we have.

**Comment by jpeg-ms** [comment]
Hi @adityakhatkhate
I had a look at how to implement support for all platforms & extensions in the plugin. I'm not sure we will merge this PR as we should be using the CLI for non supported platforms.

But I'm currently having issues while trying to upload a .zip or .msi file to a Unity app (using fastlane, CLI and portal). We'll let you know once we know more why uploads fail.

**Comment by adityakhatkhate** [comment]
Hi @jpeg-ms 
ok, thats a bummer. We would have to make changes to all our automation pipelines.

As for using a .zip for a unity app with cli, i was experiencing the same issue when i was testing the CLI where it complained the following : 

```Release upload was aborted
Error: release binary file uploading failed: HTTP 422 Unprocessable Entity```

To verify if this was across all platforms, i tried to upload the same zip to a `WPF` platform app and it uploaded successfully. I would still expect the upload to succeed when platform is `Unity`.

Hope this helps.

**Comment by jpeg-ms** [comment]
After discussing with my team, we decided to roll out a fix for the API rejecting .zip & .msi uploads for Windows apps. We will also go ahead and merge the above PR #139 and release a new version of this plugin soon. So please hang on tight!

**Comment by niezbop** [comment]
Seconded, our team needs this as well.

What's the ETA on this @jpeg-ms ? We're currently in the middle of moving our pipeline to support AppCenter, so if you need people to test your work in real situations, I'll be glad to help any way I can. We have projects setup to use the appcenter plugin on both Mac and Windows.

**Comment by jpeg-ms** [comment]
Hi everyone,
Sorry this is not completed yet as we are dealing with a couple of other issues. I'm trying to make sure that we will really go ahead with this and will try to get a release out soon. Sorry for the delays.

**Comment by jpeg-ms** [comment]
Hey folks! We've now released v1.6.0 with support for all known platforms & file extensions.
I'm closing this but would love to hear your feedback.

**Comment by niezbop** [comment]
Works like a charm! Tested on both our Windows and Mac projects. Thanks @jpeg-ms 

However, there is a warning on windows and mac when uploading builds that have a dot in their file name:
```
[11:28:54]: ------------------------------
[11:28:54]: --- Step: appcenter_upload ---
[11:28:54]: ------------------------------
[11:28:54]: Extension not supported: '.1_win32.zip'. Supported formats for platform 'windows': .appx .appxbundle .appxupload .msix .msixbundle .msixupload .zip .msi
[11:28:54]: The current operation might fail, trying anyway...
[11:28:55]: Fields `version` and `build_number` are not supported for files of type .1_win32.zip
[11:28:55]: The current operation might fail, trying anyway...
[11:28:55]: Starting release upload...
[11:28:55]: Uploading release binary...
[11:28:59]: Binary uploaded
```
Nothing major, but our build is called `Product_1.1.2_win32.zip` and that's not really an extension issue then. Note that all of our builds follow similar naming conventions and only mac and windows have such a warning, iOS and Android are fine.
I'm not sure that's something you want to address, but that's the only negative feedback I'd give on that!

Thanks again!

**Comment by jpeg-ms** [comment]
Ah, thanks for the heads up! I guess the "full" extension function will need to be special cased for macOS `.app.zip`, then.

**Comment by adityakhatkhate** [comment]
@jpeg-ms Plugin 1.6.0 works great. I was able to successfully upgrade all platforms. Appreciate all your work. Thanks!
