### ISSUE TITLE
Add timeout usage to DSYM uploads too.

### ISSUE THREAD

**Issue by jaleksynas** [microsoft/fastlane-plugin-appcenter#137]
The IPA upload respects the timeout option from #91 ; however the timeout option should also be used for the _any_ upload like the DSYMs.

I often see successful uploads of the IPA only to fail on DSYM upload.

**Comment by Jauzee** [comment]
Any way to skip uploading DSYMs currently?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
