### ISSUE TITLE
Getting error while running appcenter_upload for iOS build (available_options': [!] uninitialized constant Fastlane::Actions::SharedValues::GRADLE_AAB_OUTPUT_PATH (NameError))

### ISSUE THREAD

**Issue by joypatel04** [microsoft/fastlane-plugin-appcenter#138]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am using fastlane-plugin-appcenter to upload my build to appcenter. I am only passing 4 params as describe below and it's throwing an error. I am trying to upload iOS build and it's asking the path for Android bundle file

```
appcenter_upload(
      api_token: "1*************************0f8",
      owner_name: "B***********I",
      app_name: "B***************2",
      ipa: "./ios/appcenter/b**************e.ipa",
    )
```

## Error

```
/Users/********/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-appcenter-1.5.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:345:in `available_options': [!] uninitialized constant Fastlane::Actions::SharedValues::GRADLE_AAB_OUTPUT_PATH (NameError)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[### Captured Output

Command Used: `action appcenter_upload`
<details><summary>Output/Log</summary>

```

DEBUG [2019-10-24 16:22:15.32]: Checking if there are any plugins that should be loaded...
DEBUG [2019-10-24 16:22:15.42]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2019-10-24 16:22:15.55]: gem 'fastlane-plugin-appcenter' is already installed
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-appce  | 1.5.0   | appcenter_fetch_devic  |
| nter                   |         | es appcenter_upload    |
+------------------------+---------+------------------------+

Loading documentation for appcenter_upload:

+------------------------------------------------------------------------------+
|                               appcenter_upload                               |
+------------------------------------------------------------------------------+
| Distribute new release to App Center                                         |
|                                                                              |
| Symbols will also be uploaded automatically if a `app.dSYM.zip` file is      |
| found next to `app.ipa`. In case it is located in a different place you can  |
| specify the path explicitly in `:dsym` parameter.                            |
|                                                                              |
| Created by Microsoft                                                         |
+------------------------------------------------------------------------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: uninitialized constant Fastlane::Actions::SharedValues::GRADLE_AAB_OUTPUT_PATH

URL: https://api.github.com/search/issues?q=uninitialized%20constant%20Fastlane%3A%3AActions%3A%3ASharedValues%3A%3AGRADLE_AAB_OUTPUT_PATH+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue


```
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/T1***********Q/BPC****KD/********************i7"
    # cocoapods
    
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(type: "adhoc", app_identifier: 'org.************.**ai', readonly: true)
  end

  desc 'Fetch certificates. Build the iOS application.'
    lane :buildStaging do
    certificates
    # build_number = get_build_number()
    # increment_build_number(build_number: build_number)
    
    gym(
      scheme: 'be****************e.staging',
      workspace: './be************ile.xcworkspace',
      configuration: 'release',
      output_directory: './appcenter',
      export_method: 'ad-hoc',
      export_options: {
        method: 'ad-hoc',
        provisioningProfiles: { 
          'org.***************.*i' => 'match************** *******.ai'
        }
      }
    )
  end

  lane :uploadApp do
    appcenter_upload(
      api_token: "1*************************0f8",
      owner_name: "B***********I",
      app_name: "B***************2",
      ipa: "./ios/appcenter/b**************e.ipa",
    )

  end  

  desc 'Fetch certificates, build and upload to App Center.'
  lane :appcenter do
    buildStaging
    uploadApp
  end

  # desc "Runs all the tests"
  # lane :test do
  #   scan
  # end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # desc "Deploy a new version to the App Store"
  # lane :release do
    # match(type: "appstore", readonly: true)
    # snapshot
    # gym # Build your app - more options available
    # deliver(force: true)
    # frameit
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "org.*************.*i" # The bundle identifier of your app
apple_id "c*************.*i" # Your Apple email address

apple_dev_portal_id "c*************.*i"  # Apple Developer Account
itunes_connect_id "c*************.*i"     # App Store Connect Account

team_id "4*********S" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status  |
| ------------------------- | ------- | -------------- |
| fastlane-plugin-appcenter | 1.5.0   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
| highline                  | 1.7.10       |
| excon                     | 0.67.0       |
| plist                     | 3.5.0        |
| babosa                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| fastlane-plugin-appcenter | 1.5.0        |
</details>

*generated on:* **2019-10-24**
</details>

**Comment by lacostej** [comment]
You are using fastlane 2.28.3, released in 2017, but `Fastlane::Actions::SharedValues::GRADLE_AAB_OUTPUT_PATH` was added as part of https://github.com/fastlane/fastlane/pull/12568 released in 2018. 

Solution: upgrade fastlane in your project.

**Comment by phillipleblanc** [comment]
@joypatel04 Hopefully upgrading fastlane fixed this for you. I'm going to close this issue, feel free to re-open if you are still seeing problems.

**Comment by below** [comment]
I am running fastlane 2.136.0, but I am still getting this error. What other info can I provide?
