### ISSUE TITLE
Merge AppCenter plugins

### ISSUE THREAD

**Issue by leszko11** [microsoft/fastlane-plugin-appcenter#149]
Hi guys!
Isn't be great to have other existing AppCenter plugins merged into this one? Currently, there are 3 duplicated plugins for fetching the latest release build number. 

I am also looking for a plugin, which returns `short_version` from AppCenter api response. I can create it, but it will be another AppCenter related plugin to install

**Comment by phillipleblanc** [comment]
Hey @leszko11 - I'm not aware of these other plugins, can you point them to me? If there is functionality that people are looking for, I agree it would be good to integrate that here.

**Comment by leszko11** [comment]
Thanks @phillipleblanc for a quick response. There are 3 different plugins, that return `version` from api response, so I think it's a feature people looking for. 

https://github.com/jspargo/fastlane-plugin-latest_appcenter_build_number
https://github.com/zondezatera/fastlane-plugin-appcenter_get_recent_release_version
http://www.rubydoc.info/gems/fastlane-plugin-appcenter_get_version/0.1.0

**Comment by Jasjah** [comment]
Good idea @leszko11, hope so it will be merged and added soon :)

**Comment by phillipleblanc** [comment]
Unfortunately we won't have much time to implement this ourselves, but if someone wants to create a PR to add this we will review it.

**Comment by jspargo** [comment]
Hey @leszko11 - I’m the author of [fastlane-plugin-latest_appcenter_build_number](https://github.com/jspargo/fastlane-plugin-latest_appcenter_build_number).

Let me see if I can get a PR to bring the functionality from my plugin into this repository. It’s worth saying mine returns the value from `version`, but it wouldn’t be too difficult to update it to return `short_version` as a different method or by specifying a parameter.

**Comment by jp-andre** [comment]
Hi all! Thanks a lot for your interest in this plugin, and even more for contributing to it (kudos to @jspargo).

Purely out of curiosity, I'd like to know some use cases for these actions. This would help us better understand the requirements :)
