### ISSUE TITLE
"your appcenter account name" = "Username"?

### ISSUE THREAD

**Issue by janpio** [Microsoft/fastlane-plugin-appcenter#15]
Is the value of `owner_name` what I get from the "Username" field on https://appcenter.ms/settings/profile?

**Comment by lumaxis** [comment]
Yes, exactly! For organizations, it's what you would find as the last part under "Organization URL" here:
<img width="647" alt="screenshot 2017-11-30 15 07 57" src="https://user-images.githubusercontent.com/406937/33434691-4fb75b76-d5e0-11e7-8bc6-225f508b33f2.png">

**Comment by janpio** [comment]
If that page has a similarly nice URL (I am not part of an org), this would be nice to have in the docs :)

**Comment by leynercastillo** [comment]
Another information to this issue, if you have tried everything XD, it is to try to create the api token full access, not read only.
