### ISSUE TITLE
Seems download url for sparkle works isn't correctly

### ISSUE THREAD

**Issue by overtake** [microsoft/fastlane-plugin-appcenter#153]
Hi, i've noticed the download link for zip isn't correct.  The link is linked to hockeyapp which is will be closed soon.

e.g
https://api.appcenter.ms/v0.1/public/sparkle/apps/f012091f-35d9-47bb-b3db-9cbd3b0232d3

**Comment by Ajaykn21** [comment]
Hi @overtake 
Please ignore those download url's, we will have those links available irrespective of HockeyApp shutdown.

**Comment by overtake** [comment]
It is ok? But it looks like "Download Count" not increments when users are downloading new version from legacy url.

**Comment by Ajaykn21** [comment]
Yeah, we are currently evaluating to show the Download count for Sparkle.
But aside that, there should not be any issue in sparkle updates.

**Comment by overtake** [comment]
Ok, thanks.  And one more question there. If you decide in the future to replace download url. Will be it a problem for example if i don't update the plugin?

**Comment by Ajaykn21** [comment]
Hi @overtake,
You should see no issues.
I assume you have followed this.
https://docs.microsoft.com/en-us/appcenter/distribution/sparkleupdates.
