### ISSUE TITLE
wildcard for distribution not working

### ISSUE THREAD

**Issue by romk1n** [microsoft/fastlane-plugin-appcenter#155]
As per example in the readme we used `*` for distributions groups however it resulted in the following error:

```
[14:51:21]: Not found, invalid distribution group name
[14:51:21]: group '*' was not found
```

**Comment by phillipleblanc** [comment]
@romk1n - Which action are you using? `*` is only supported for the `appcenter_fetch_devices` action, not the `appcenter_upload` action.

**Comment by romk1n** [comment]
Argh my bad I have misread didn’t realise it is only for fetch. What’s the best way to distribute to all groups if needed ?

**Comment by jpeg-ms** [comment]
@rom1k At the moment we do not have this feature. You can list all groups manually in the Fastfile, separating them with commas `,`. See also #155 as mentioned above.

**Comment by phillipleblanc** [comment]
Closing this as #150 was merged.
