### ISSUE TITLE
app_name required?

### ISSUE THREAD

**Issue by janpio** [Microsoft/fastlane-plugin-appcenter#16]
With HockeyApp it was enough to upload an apk or ipa and the app figured out the name by itself by extracting it from the app. From reading the params of this plugin, this doesn't seem to be possible with AppCenter. Is this correct?

**Comment by derpixeldan** [comment]
Unfortunately it's not possible.

**Comment by punksta** [comment]
Hi, it's still not possible? @derpixeldan
There is no api for finding apps by package name/bundle id?

initial app name can be get from build itself.  `android:label="@string/app_name"` for android and bundle name for ios.

**Comment by subinsv** [comment]
@derpixeldan
Is there any technical reason why it is not possible. Because we had the functionality in Hockey plugin.

**Comment by derpixeldan** [comment]
Basically by design, in HockeyApp you had to specify the bundle id per app, but not in App Center.

**Comment by subinsv** [comment]
Thanks @derpixeldan
