### ISSUE TITLE
Exception while uploading dsym

### ISSUE THREAD

**Issue by Semmu** [microsoft/fastlane-plugin-appcenter#162]
Hi!

When uploading dsym using this plugin, we get an exception:
`[20:03:10]: no implicit conversion of Symbol into Integer
[20:03:10]: Backtrace:
	/Users/jenkins/ios-workspace/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-appcenter-1.6.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:56:in []='
...`

I think it is because the plugin converts a HashMap to a flat array, but then it tries to use it as a HashMap: https://github.com/microsoft/fastlane-plugin-appcenter/blob/master/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L56

Does anyone else also face the same issue and is my assumption correct?

Thanks in advance!

**Comment by Ajaykn21** [comment]
We are not seeing any issue.
Are you using latest version of plugin ?

**Comment by phillipleblanc** [comment]
Closing this issue, feel free to re-open if it is still occurring.
