### ISSUE TITLE
Ability to set different values of "notify_testers" option for various distribution groups

### ISSUE THREAD

**Issue by idan676** [microsoft/fastlane-plugin-appcenter#165]
We have various distribution groups for our application. Some only need access, others also need an email. As I see API allows to do this (from [appcenter_upload_action.rb](https://github.com/microsoft/fastlane-plugin-appcenter/blob/0f5c68e6112b0dc312be6b04e414cd177f2bdb5b/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L194-L199)).

**Comment by jpeg-ms** [comment]
I think we should consider having another action to re-distribute existing releases to other destinations. Then this kind of granularity could easily be implemented.

**Comment by idan676** [comment]
> I think we should consider having another action to re-distribute existing releases to other destinations. Then this kind of granularity could easily be implemented.

Great, thank you!

**Comment by jp-andre** [comment]
Let me close this for now as duplicate of #166.
