### ISSUE TITLE
what can I get release_id?

### ISSUE THREAD

**Issue by lowfiend** [microsoft/fastlane-plugin-appcenter#167]
I see app center api

`{
  "app_name":"{app-name}",
  "app_display_name":"{app-display-name}",
  "release_id":"123",
  "platform":"Android",
  "uploaded_at":"2018-07-17T20:46:14Z",
  "fingerprint":"0abed1269e4ae3bf524e4cc7165f4f34",
  "release_notes":"Merge pull request #756 from Microsoft/fix/fix-transmission-target-selection\n\nFix regression in EventActivityUtil",
  "version":"74",
  "short_version":"1.7.0",
  "min_os":"4.0.3",
  "mandatory_update":true,
  "size":2634279,
  "provisioning_profile_name":null,
  "provisioning_profile_type":null,
  "bundle_identifier":"com.microsoft.appcenter.test.jcenter",
  "install_link":"https://install.appcenter.ms/orgs/{org-name}/apps/{app-name}/releases/123?source=email",
  "icon_link":"https://rink.hockeyapp.net/api/2/apps/45d1d9f624924e4686447190345325f3?format=png",
  "distribution_group_id":"1a5a0605-4b9c-4de2-9a35-t569456df0cc",
  "installable":true,
  "sent_at":"2019-05-16T23:20:08.7799314Z",
  "app_id":"f37c6194-9ac9-4504-be61-55re334r5649"
}`

I use #{lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]['version']}  can get version but I use #{lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]['release_id']}  is empty

what can I get release_id?

**Comment by lowfiend** [comment]
I puts lane_context[SharedValues::APPCENTER_BUILD_INFORMATION] , and I find the key is "id" not  release_id.

**Comment by jerietve** [comment]
I'm glad you found the answer. The return value must be a release, hence the property is just called `id`.
