### ISSUE TITLE
Release_notes and File.read

### ISSUE THREAD

**Issue by ff-ahumberston** [microsoft/fastlane-plugin-appcenter#168]
I'm trying to use the plugin (1.7.0) to upload release notes from a file via the command line using File.read, which appears to be the standard method for reading in text from a file within Fastlane.

Using: 

bundle exec fastlane --verbose run appcenter_upload api_token:"XXX" owner_name:"XXX" app_name:"XXX-iOS" app_os:ios file:"XXX.ipa" release_notes:File.read\("changes.txt"\)

Results in the Release Notes on App Center being set to 
File.read(changes.txt)

Can anybody offer any guidance ?

**Comment by joabalea** [comment]
@ff-ahumberston 
Can you try something like:

`bundle exec fastlane --verbose run appcenter_upload api_token:"XXX" owner_name:"XXX" app_name:"XXX" app_os:ios file:"test.ipa" release_notes:"$(cat changes.txt)"`

**Comment by ff-ahumberston** [comment]
Thanks Joris (@joabalea)

I'd tried multiple variations, but this one works.
