### ISSUE TITLE
Figure out OS and Platform automatically

### ISSUE THREAD

**Issue by janpio** [Microsoft/fastlane-plugin-appcenter#17]
When you try to upload an app with an unknown `app_name` you get these prompts:

```
[20:14:25]: App with name FastlaneExample not found, create one? (y/n)
y
[20:14:30]: Select OS
1. Android
2. iOS
?  1
[20:14:49]: Select Platform
1. Java
2. React-Native
3. Xamarin
?  1
```

* OS: Android or iOS could be selected by my choice of apk or ipa file to upload. Or am I missing complexity here?
* Platform is not defined by any of the params, but maybe can also be deduced from the app file?

**Comment by janpio** [comment]
Interesting, the server seems to know about the platform of an uploaded file by itself anyway:

> [20:33:52]: Error uploading binary 422: {"status"=>"error", "message"=>"Platform does not match. Expected value: Android. Actual value: iOS."}

Accidentally uploaded an ipa for the name of an app that was defined as "Android" before.

**Comment by janpio** [comment]
As a workaround/stopgap there could/should be a param for `os` and `platform` where you can specify these values to not get prompted.

**Comment by janpio** [comment]
Some more thinking about that:

* OS should be deduced from `ipa`/`apk` (Alternative: platform for lane / default platform)
* Platform should be added as param that can be set, if not set default is Obj-C/Java as a sensible default

**Comment by lumaxis** [comment]
Thanks @janpio, good thoughts in there!

@evkhramkov I think detecting the OS should be relatively straight forward, given that the `.ipa` and `.apk` file extensions are pretty reliable indicators.
@janpio What exactly did you mean by "(Alternative: platform for lane / default platform)"?

Given the fact that App Center currently does not support changing the Platform after the app is created, I'd be a bit wary of automatically falling back to a default. @janpio Why do you think it is important to have these values be settable as parameters? The app creation should be a one-time thing and I thought prompting the user in that case was a sensible thing to do.

**Comment by janpio** [comment]
> @janpio What exactly did you mean by "(Alternative: platform for lane / default platform)"?

You can access the "platform" of your lane (or the default platform, if your lane is run without one) in your action: https://github.com/fastlane/docs/pull/477/files (merged, but not published to the Fastlane docs yet). So `fastlane ios appcenter` can access `ios`, `fastlane android appcenter` => `android`. 
But using ipa/apk is probably better as it reflects the actual file, not what lane was called.

> Why do you think it is important to have these values be settable as parameters? The app creation should be a one-time thing and I thought prompting the user in that case was a sensible thing to do.

That's not wrong, but for me 100% of the cases I will want Obj-C/Java selected here. If you think this doesn't apply to enough of the users, maybe the param as optional, prompting only if not set? (I would then use the ENV variable to never have to manually set this when calling the actions).

**Comment by donnes** [comment]
Any update about this issue?

**Comment by kemalenver** [comment]
@lumaxis there is a valid use case for this happening automatically (Hockey currently allows apps to be created with no user intervention). My company creates alpha builds for QA based on branch names, on a CI we don't have access to.  See my issue for further explanation: https://github.com/Microsoft/fastlane-plugin-appcenter/issues/52

**Comment by evkhramkov** [comment]
> I think detecting the OS should be relatively straight forward
Yes, that is right, but we still need to specify platform (java, react-native, xamarin, etc)
Also `ipa` and `apk` are optional, upload action can be used only for symbol uploads

So I'd suggest adding two optional parameters `os` and `platform` which will be used as defaults in case of not found app.

cc @derpixeldan

**Comment by derpixeldan** [comment]
To unify the conversation handling in referenced ticket.
