### ISSUE TITLE
Could not find action, lane or variable 'build_app'

### ISSUE THREAD

**Issue by YanxiFeng** [microsoft/fastlane-plugin-appcenter#170]
I run 'fastlane dev' in terminal, then this error occurred.  
`Could not find action, lane or variable 'build_app'. Check out the documentation for more details: https://docs.fastlane.tools/actions`

**Comment by jpeg-ms** [comment]
Sorry but this does not seem related to appcenter plugin itself. We only provide two actions, none of them is called `build_app`.

**Comment by phillipleblanc** [comment]
Closing this issue, feel free to re-open if you are still experiencing a problem.
