### ISSUE TITLE
{"error"=>{"code"=>"BadRequest", "message"=>"Validation error: Validation is failed"}}

### ISSUE THREAD

**Issue by janpio** [Microsoft/fastlane-plugin-appcenter#18]
I got this error message several times when uploading apps now:

```
[21:09:26]: Error creating app 400: {"error"=>{"code"=>"BadRequest", "message"=>"Validation error: Validation is failed"}}
```

Is there any way to find out what was is actually going wrong?

**Comment by janpio** [comment]
Might be it didn't like the `(` in my `app_name`. Not sure.

**Comment by derpixeldan** [comment]
@janpio I know it's been over a year already. In case of any issues please reach out to us in support (blue button) on App Center so we can help you faster.
