### ISSUE TITLE
Get last build number from AppCenter

### ISSUE THREAD

**Issue by ramilexe** [microsoft/fastlane-plugin-appcenter#180]
Is it possible to automatically increment build number based in AppCenter not in project file?

**Comment by jp-andre** [comment]
Hi @ramilexe

It's not quite clear what you are referring to? Are you talking about the `build_number:` property in the Fastfile for `appcenter_upload` action? If then, how do you want it increment to increment?
This build number is only required for macOS `.pkg` and `.dmg` files for which App Center will not extract the information automatically, and that can only be given by whoever compiles the app.

**Comment by Ajaykn21** [comment]
@ramilexe Does the above comment resolve your query.
Please revert back to us if you still have any other questions.
