### ISSUE TITLE
Release type not available

### ISSUE THREAD

**Issue by ir2pid** [microsoft/fastlane-plugin-appcenter#181]
I don't find the option to set the release type when uploading to appcenter.
Which would include store, alpha, beta etc.

**Comment by Ajaykn21** [comment]
Hi @ir2pid , 
Are you referring to the ReleaseType when creating the app,
<img width="679" alt="image" src="https://user-images.githubusercontent.com/40024974/71710330-1813f580-2e3f-11ea-8d74-d7dab89abd22.png">

If so, its just a metadata to capture, and has nothing to do when uploading the releases.
