### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by naveenira** [microsoft/fastlane-plugin-appcenter#182]
Getting error via Fastlane

**Log**
[14:45:58]: [32m--- Step: appcenter_upload ---[0m
[14:45:58]: [32m------------------------------[0m
[14:45:58]: Starting release upload...
[14:45:59]: re-raise the exception unless it's something we're OK with ignoring Internal Service Error, please try again later

**Comment by Ajaykn21** [comment]
Hi @naveenira ,
We have seen few issues in out internal service and it is fixed now.
Please let us know if you are facing still.

**Comment by naveenira** [comment]
> Hi @naveenira ,
> We have seen few issues in our internal service and it is fixed now.
> Please let us know if you are facing still.

@Ajaykn21 It's working fine now. thanks. Can you please close this issue.

**Comment by naveenira** [comment]
> Hi @naveenira ,
> We have seen few issues in our internal service and it is fixed now.
> Please let us know if you are facing still.

@Ajaykn21 It's working fine now. thanks. Can you please close this issue.

**Comment by ajeetvolvo** [comment]
how did you fix   this ? i am also facing the same issue.

**Comment by EdinSe** [comment]
Getting following error via fastlane

Log
[21:18:26]: Starting release upload...
[21:19:26]: Internal Service Error, please try again later
+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | opt_out_usage              | 0           |
| 2    | Verifying fastlane version | 0           |
| 3    | default_platform           | 0           |
| 4    | last_git_commit            | 0           |
| 5    | get_version_name           | 0           |
| 6    | get_version_code           | 0           |
| 7    | git_branch                 | 0           |
| 💥   | appcenter_upload           | 61          |
+------+----------------------------+-------------+
[21:19:26]: fastlane finished with errors
[!] Internal Service Error, please try again later
