### ISSUE TITLE
dSYM is ignored when uploading Mac app

### ISSUE THREAD

**Issue by triplef** [microsoft/fastlane-plugin-appcenter#183]
Uploading a Mac app to App Center by specifying both "file" and "dsym" options ignores the dSYM file and only uploads the app.

This seems to be due to AppcenterUploadAction only checking for an ".ipa" file extension, whereas macOS apps will be using a .zip (or possibly .pkg) extension:
https://github.com/microsoft/fastlane-plugin-appcenter/blob/8b4fa09b414ba563bea32a3a0c1db256a7dd8623/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L39

As a workaround one can first upload the app and then upload the dSYM separately using the "upload_dsym_only" option.

**Comment by jp-andre** [comment]
We have merged a PR that should solve this issue and published a new release (1.8.0). Please reopen if there are stil issues.
