### ISSUE TITLE
Just upload provisioning without new build

### ISSUE THREAD

**Issue by gbarnett** [microsoft/fastlane-plugin-appcenter#184]
In the appcenter dashboard you can just update the provisioning files attached to the build without having to locally create and resign a build. Is there functionality to do this with this plugin? 

Thanks!

**Comment by jp-andre** [comment]
We do not support this scenario in the plugin. A PR to address this would be welcome, but we do not plan on implementing this ourselves.
I will close this for now, as there have not been any upvotes for 24 days.
