### ISSUE TITLE
Download dSYM with fastlane then upload them to crashlytics

### ISSUE THREAD

**Issue by ARamy23** [microsoft/fastlane-plugin-appcenter#187]
I want to upload dSYM to Crashlytics after release is done via App center, but I couldn't find anything similar to my use case, is there a way to automate the process of manually downloading dSYM from the builds section and uploading it Crashlytics?

**Comment by jp-andre** [comment]
Hi @ARamy23 
I don't think this is a feature that we intend to support at the moment.
Have you considered using App Center's diagnostics?
