### ISSUE TITLE
Error 403 after App rename using Dashboard and then CLI

### ISSUE THREAD

**Issue by k-kruusi** [microsoft/fastlane-plugin-appcenter#189]
Essentially the app was renamed through the dashboard months ago, and the fastlane script was run and didnt give any issues until recently.

To address the issue after googling it I used CLI to update the app name & app url to match. However after doing so we get :
[10:43:48]: Starting release upload...
[10:43:48]: Error 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}
[10:43:48]: Starting dSYM upload...
[10:43:48]: Error 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}

App Name matches the name specified in "appcenter apps list" minus the owner name. yet still has this forbidden error.

**Comment by jp-andre** [comment]
Hi there,
403 Forbidden means there is likely a permission error. It could be because the API token was revoked. Could you try again with a new App Center API token, or the one you've used with the CLI?

**Comment by pellet** [comment]
This seems to be an issue relating to authentication with google based accounts.
Our upload account uses google auth and when I logged in with it, it did not have the same access as expected.
Once I removed all the access settings from a microsoft based account and then re-added the settings, it now had access.

**Comment by jp-andre** [comment]
Okay so if I understand you correctly, you are now able to use the fastlane plugin without 403 error?

**Comment by pellet** [comment]
> Okay so if I understand you correctly, you are now able to use the fastlane plugin without 403 error?

Sorry, I should have been more specific.  I am not using the fastlane plugin, I'm assuming it is just a thin wrapper around the CLI and you should have the same issue when using the CLI.

**Comment by jp-andre** [comment]
> Sorry, I should have been more specific. I am not using the fastlane plugin, I'm assuming it is just a thin wrapper around the CLI and you should have the same issue when using the CLI.

This plugin is completely independent from the CLI, even the same people maintain both :) This plugin is really just a small ruby plugin for fastlane while the CLI is built on Node 10.

Let's see if @k-kruusi has managed to unblock himself.
Note: both the org/user name and app name should be those coming from the URL.

**Comment by pellet** [comment]
> This plugin is completely independent from the CLI, even the same people maintain both :) This plugin is really just a small ruby plugin for fastlane while the CLI is built on Node 10.
> 
> Let's see if @k-kruusi has managed to unblock himself.
> Note: both the org/user name and app name should be those coming from the URL.
Ah yeah I realize that now... I was using a cake plugin which was just a wrapper around the CLI.
This could still be the same issue though which is some sort of back end authentication issue after renaming an app.
Try logging into appcenter from the account you upload the app from and see if you can view the app's releases and can upload ok with it, if you can't see any releases it might be the same issue I had.

**Comment by phillipleblanc** [comment]
@k-kruusi - Were you able to figure out this issue?

**Comment by yujincat** [comment]
Closing the issue as the thread has not received any feedback for a month.
