### ISSUE TITLE
`app_name` is actually more `app_slug`?

### ISSUE THREAD

**Issue by janpio** [Microsoft/fastlane-plugin-appcenter#19]
Seems what I supply as `app_name` is actually used in the URL directly:
```
[21:03:08]: bad URI(is not URI?): /v0.1/apps/piotrowski/FastlaneExample (iOS)
```
(note the space in the app name)

On the other hand later in the process (if I replace the ` ` with `-` to make it work) the value seems to be used as a kind of "name":
```
[21:08:43]: App with name FastlaneExample-(iOS) not found, create one?
(y/n)
y
```

The app is actually created with this `slug` as name then as well, which makes for awkward names in the UI everywhere (as renaming in the web UI also seems to be broken).

**Comment by evkhramkov** [comment]
Yes, you're right. We can consider adding `app_display_name` prompt to clarify that
cc @derpixeldan thoughts?

**Comment by derpixeldan** [comment]
To unify the conversation handling in referenced ticket.
