### ISSUE TITLE
Missing required params from body: build_version, unique_identifier

### ISSUE THREAD

**Issue by nazrdogan** [microsoft/fastlane-plugin-appcenter#196]
i m getting error when i try to upload app iOS build like this. 
`build_app(workspace: "***.xcworkspace", scheme: "***", skip_codesigning:true, export_team_id:ENV['DLV_TEAM_ID'], export_method: "ad-hoc")`

`Error uploading binary 400: {"error"=>"Error: Missing required params from body: build_version, unique_identifier, Service id: 2d9b3b5a-c954-4fe3-aa16-687e26904ba0"}`

**Comment by Coly010** [comment]
+1 Also receiving this error after building and exporting App with xcodebuild and a App Store Distribution Profile: iPhone Distribution

**Comment by Seanmcn** [comment]
I'm also stuck with this issue at the minute, has anyone managed to resolve / workaround?

**Comment by nazrdogan** [comment]
@Seanmcn  for me if app signed properly its not happening

**Comment by ResonantEdge** [comment]
> @Seanmcn for me if app signed properly its not happening

If I may ask, what are you using to sign the app?

**Comment by nazrdogan** [comment]
@ResonantEdge  I used `match` to create profile and certs etc.. then normally signed with `build_app`

**Comment by asalom** [comment]
I was able to work around this issue for Custom builds by zipping the binary two times. I guess App Center makes some processing in the files contained in a zip, unless they are a zip
