### ISSUE TITLE
Ability to trigger an app center build via Fastlane

### ISSUE THREAD

**Issue by anthonycastelli** [microsoft/fastlane-plugin-appcenter#200]
We use the App Center build action on our iOS and Android apps to avoid having to upload binaries. Can we get an action implemented to essentially run the build action?

**Comment by ajaykn** [comment]
Hi @anthonycastelli , thanks for requesting the feature request.
If you want to use the fastlane, just for triggering the build in App Center, 
Then we recommend you to go with [App Center CLI](https://github.com/microsoft/appcenter-cli)
and command is `appcenter build queue`

If you are still looking for this as fastlane action, we will keep this  ticket open and see if more upvotes comes, then we can triage and pick it up.
Meantime, if interested, we welcome you to raise the community PR's too. :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
