### ISSUE TITLE
Supported platforms not up to date with backend

### ISSUE THREAD

**Issue by lacostej** [microsoft/fastlane-plugin-appcenter#207]
https://github.com/microsoft/fastlane-plugin-appcenter/blob/0f1558747423a523ab0a0e0dd08716bc939171af/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L254-L260

E.g. for iOS, missing "Unity" and maybe "Cordova"
<img width="311" alt="image" src="https://user-images.githubusercontent.com/24282/80277283-381d3c80-86ee-11ea-86e4-660c477d0906.png">

Etc.

**Comment by jp-andre** [comment]
Thanks for your report. Sorry for the super long delay in responding here.
