### ISSUE TITLE
Some backend errors are swallowed (400s, 500s).

### ISSUE THREAD

**Issue by lacostej** [microsoft/fastlane-plugin-appcenter#208]
```
[18:12:09]: Error creating app 400: {"error"=>{"code"=>"BadRequest", "message"=>"Validation error: \"Unity\" is not a valid platform for OS \"macOS\"!"}}
```

400 errors are caught and not turned into exceptions
https://github.com/microsoft/fastlane-plugin-appcenter/blob/3d1e144a55e4e59c9487bb25363c6bf00612a23a/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb#L562-L564

It should `use user_error!` here.  Same for most errors in most calls of this file.

Note that this helper file should be refactored. Authorization and common error handling should be done in one place. See Fastlane spaceship module for ideas.

**Comment by Hiroto-N** [comment]
+1 working on something now but the helper class seems to be quite a bit of copy and paste which makes it hard to contribute or add new functionality.

In addition to the above I would suggest that if the current "silent" behaviour is desired it should be a configuration option instead so it's opt-in

**Comment by jp-andre** [comment]
Hi, you're both right. The helper code would benefit from a code cleanup. Contributions are welcome!

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
