### ISSUE TITLE
Show summary of params before starting

### ISSUE THREAD

**Issue by janpio** [Microsoft/fastlane-plugin-appcenter#21]
It would be very handy if `appcenter_upload` would show a summary of all the params submitted before starting to work. This would make debugging problems and failures much easier.

Example:
Ran a `android` lane. Selected Android as OS. Upload failed with "Platform does not match. Expected value: Android. Actual value: iOS". Turns out I had copied over the lane from `ios` and forgot to change `ipa` to `apk` and was also upload an .ipa file. Seeing this output on the command line would have sped up finding this quite a lot.

**Comment by derpixeldan** [comment]
Thanks for the suggestion we don't consider to do this at the moment.
