### ISSUE TITLE
appcenter_upload frequently returns Net::OpenTimeout

### ISSUE THREAD

**Issue by adamhaafiz** [microsoft/fastlane-plugin-appcenter#211]
Hello,

In our fastlane script we use `appcenter_upload` to upload and distribute our IPA. The relevant script is as follows:

```
  lane :deploy_debug do
    unit_tests
    gym(
        ...omitted...
    )

    appcenter_upload(
      owner_name: "Peaks",
      owner_type: "organization", 
      app_name: "Peaks-Test",
      file: "./build/#{output_name}",
      destinations: "*"
    )
  end
```

However we've noticed that the `appcenter_upload` step frequently returns a `Net::OpenTimeout` error, causing the entire build to fail:
![Screenshot 2020-05-06 at 10 37 03](https://user-images.githubusercontent.com/5069753/81156022-d5496200-8f85-11ea-91fe-17075a55e673.png)

If we check manually in App Center, the binary has indeed been **uploaded but it is not distributed to any of our testers**. The success rate of this step is currently around 20%. Sometimes we have to retry up to 3 times to get the step to succeed.

The build machine is running macOS 10.15.4, fastlane 2.144.0 and fastlane-plugin-appcenter 1.8.0.

**Comment by jp-andre** [comment]
Hi, have you considered setting the `timeout` option? Or `APPCENTER_DISTRIBUTE_TIMEOUT` environment variable.

Unfortunately due to a limitation we didn't find a workaround for yet, we are not able to fix the timeout issues for dSYM uploads, but it should be fine for all applications. See also #140

**Comment by adamhaafiz** [comment]
Didn't see that parameter before, works a treat! Our uploads are a lot more consistent now. Thank you!
