### ISSUE TITLE
Failed to upload dsym, RequestBodyTooLarge

### ISSUE THREAD

**Issue by kyubuns** [microsoft/fastlane-plugin-appcenter#218]
myapp.app.dSYM.zip has 326.85 MB now.
I cannot upload dsym.

```
Error uploading dSYM 413: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:db46cbf9-701e-00c0-23de-2fa0e7000000
Time:2020-05-22T02:11:06.9856835Z</Message><MaxLimit>268435456</MaxLimit></Error>
dSYM upload aborted
```

```
fastlane (2.148.1)
fastlane-plugin-appcenter (1.8.0)
```

Can I resolve this?

**Comment by jp-andre** [comment]
Hi @kyubuns. I don't think this is a problem with the fastlane plugin itself. Have you tried uploading the same file manually through the web portal?
You may want to open an issue in [appcenter repo](https://github.com/microsoft/appcenter/issues) or contact our support if this is blocking for you.

**Comment by kyubuns** [comment]
<img width="1051" alt="Screen Shot 2020-05-25 at 13 32 37" src="https://user-images.githubusercontent.com/961165/82778397-48127280-9e8c-11ea-92cf-0deee342d4e5.png">
Thanks for the reply.
But, This is successful if I manually upload it from the website...

**Comment by jp-andre** [comment]
Interesting. I assume you've tried and failed multiple times to upload with the plugin?

**Comment by kyubuns** [comment]
Yes,
I get the same error no matter how many times I try.
I tried it again today and it didn't change.

**Comment by roeland-deca** [comment]
+1

Is there a workaround for this or any idea when there will be a fix?

**Comment by phoffer** [comment]
@roeland-deca according to [this other issue](https://github.com/microsoft/fastlane-plugin-appcenter/issues/93#issuecomment-509234694), the upload max via API (fastlane) is 256mb. That might be your issue

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
