### ISSUE TITLE
Distribute to organization Distributions Group

### ISSUE THREAD

**Issue by DIBocca** [microsoft/fastlane-plugin-appcenter#227]
We have distribution groups at organization level to manage people in multiple applications.

When uploading through the plugin, I get a forbidden when trying to setup those group as destinations.
ej

>destinations: "Collaborators, testers",

>[10:33:00]: Error getting group 403: {"error"=>{"code"=>"Forbidden", "message"=>"You do not have sufficient permission to perform this action on distribution group \"testers\""}}

**Comment by yujincat** [comment]
Hi! 

Releasing to a distribution group is only allowed to group admin and collaborator roles. Can you make sure that the user has either of the role?

**Comment by phillipleblanc** [comment]
Closing this issue, if yujincat's response didn't fix your problem feel free to comment and re-open.
