### ISSUE TITLE
Release notes clipping works incorrectly if release notes contains flags emojis  

### ISSUE THREAD

**Issue by volo-droid** [microsoft/fastlane-plugin-appcenter#229]
Recently we've updated release notes on our project and started receiving the following error for the `appcenter_upload` action:
> Error adding updating release 400: {"code"=>"bad_request", "message"=>"Error: The release notes exceeds the limit of 5000 characters."}

Even though clipping had been confirmed by the plugin few lines above:
> Release notes clipped

After enabling debug logs (using `DEBUG=1` env variable), I was able to get the clipped changelog sent to the AppCenter and check it's actual length which turned out to be `5056` (checked in Kotlin script). I assumed that had been caused by flag emojis we added recently to the release notes by the following line:
> - Add new locales: 
  bg 🇧🇬, da 🇩🇰, de_LU 🇱🇺, en_AE 🇦🇪, en_CY 🇨🇾, en_HK 🇭🇰, en_IN 🇮🇳, en_MT 🇲🇹, en_TH 🇹🇭, en_ZA 🇿🇦, 
  et 🇪🇪, fi 🇫🇮, fr_BE 🇧🇪, fr_LU 🇱🇺, hr 🇭🇷, it_IT 🇮🇹, lv 🇱🇻, lt 🇱🇹, nl_BE 🇧🇪, nl_NL 🇳🇱, 
  nb 🇳🇴, nn 🇳🇴, pt_PT 🇵🇹, sk 🇸🇰, sl 🇸🇮, sv 🇸🇪, th 🇹🇭, zh_HK 🇭🇰

A flag emoji consists of two regional indicator symbols: https://emojipedia.org/emoji-flag-sequence/ 
For example, Sweden emoji is a flag sequence combining 🇸[Regional Indicator Symbol Letter S](https://codepoints.net/U+1F1F8) and 🇪 [Regional Indicator Symbol Letter E](https://codepoints.net/U+1F1EA). 
My assumption was that those are counted by the plugin as one character due to a bug, so I removed for each flag the second regional indicator symbol, so the line became: 
> - Add new locales: 
  bg 🇧, da 🇩, de_LU 🇱, en_AE 🇦, en_CY 🇨, en_HK 🇭, en_IN 🇮, en_MT 🇲, en_TH 🇹, en_ZA 🇿,
  et 🇪, fi 🇫, fr_BE 🇧, fr_LU 🇱, hr 🇭, it_IT 🇮, lv 🇱, lt 🇱, nl_BE 🇧, nl_NL 🇳, 
  nb 🇳, nn 🇳, pt_PT 🇵, sk 🇸, sl 🇸, sv 🇸, th 🇹, zh_HK 🇭

And then the length of the whole release notes message became exactly `5000`.

**UPDATE**
After further investigation I believe, this is caused by different ways of calculating string length by Ruby on the plugin side and .NET, which AppCenter probably uses for a backend.

C#:
```c#
var text = "🇸🇪";
Console.WriteLine(text.Length);  //  ==>  4
```

Ruby:
```ruby
text = "🇸🇪"
text.length   #  ==>  2
```

Thus for a single flag emoji length returned is `4` in .NET and `2` in Ruby. Because in .NET String:
> The `Length` property returns the number of `Char` objects in this instance, not the number of Unicode characters. The reason is that a Unicode character might be represented by more than one `Char`.

**Comment by jp-andre** [comment]
Hi @volodymyr-gz,

What an amazing bug report, thanks so much for all the details! 👏

In fact we don't use .NET for this API, but Node.js. The behavior is the same as .NET though, where node will basically convert to UTF-16 and the length of a single flag emoji is 4.

I had a look but unfortunately could not find a solution yet. Those encoding issues are quite complex sometimes 😅 
Marking this as `bug` to keep track of it.

**Comment by volo-droid** [comment]
@jp-andre Happy to help!

In terms of fix, IMHO the simplest way would be to align Ruby client code with server-side check by checking the number of UTF-16 code units (each consisting of 2 bytes).
So this one:
```ruby
if release_notes.length >= Constants::MAX_RELEASE_NOTES_LENGTH
```
should be updated with:
```ruby
if release_notes.bytesize / 2 >= Constants::MAX_RELEASE_NOTES_LENGTH
```

**Comment by bitcrumb** [comment]
If I am not mistaken this is still an issue? Bumped into this myself yesterday.

**Comment by AlexApriamashvili** [comment]
I confirm this is still an issue in version `2.0.0`. I stumbled upon this due to the 🍒 emoji in one of PR titles :D

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
