### ISSUE TITLE
lane_context is wrongly filled

### ISSUE THREAD

**Issue by jukben** [Microsoft/fastlane-plugin-appcenter#23]
Hi,

Thanks for this plugin! 👍 

I've found a bug, due to [this patch HTTP request](https://github.com/Microsoft/fastlane-plugin-appcenter/blob/master/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L206). In `release = response.body` is always just `"distribution_group_name", "release_notes"` which is probably unwanted because I would expect the whole release object.

I'm willing to open pull request, just don't know if my solution is good enough. https://github.com/jukben/fastlane-plugin-appcenter/commit/95f6375567454932941c409983fc08efe9c34f47

**Comment by jeanregisser** [comment]
Having the same issue.
I noticed APPCENTER_DOWNLOAD_LINK was always nil.

**Comment by evkhramkov** [comment]
@jukben thanks for the feedback and suggested fix!
Please take a look at #24, a bit refactored fix with tests

**Comment by jukben** [comment]
Thanks for the support! I've left a comment @evkhramkov – I was almost there with my hotfix. 🕴

Next time! 😆

**Comment by evkhramkov** [comment]
@jukben @jeanregisser please update to `0.1.7`. Thanks for the feedback!
