### ISSUE TITLE
Invalid API token usage doesn't provide helpful error messaging

### ISSUE THREAD

**Issue by Mordil** [microsoft/fastlane-plugin-appcenter#233]
When using `appcenter_upload` for my organization this is the call site:

```ruby
def upload_to_appcenter(app_name, binary_filename)
  appcenter_upload(
    api_token: ENV["PK_APPCENTER_TOKEN"],
    owner_name: APPCENTER_OWNER_NAME,
    app_name: app_name,
    file: binary_filename,
    notify_testers: true
  )
  
  return "https://appcenter.ms/orgs/#{APPCENTER_OWNER_NAME}/apps/#{binary_filename}"
end
```

When running this on our Jenkins CI and getting to this step, I get the following error message:

```
[17:45:28]: ------------------------------
[17:45:28]: --- Step: appcenter_upload ---
[17:45:28]: ------------------------------
[17:45:29]: App with name **** not found, create one?
[17:45:29]: Could not retrieve response as fastlane runs in non-interactive mode
```

On a whim I changed the API token to a fresh one (the older one worked on Friday, but was presumably deleted and my team wasn't notified) and now the builds work.

EXPECTED OUTCOME:

I would expect the step would be able to diagnose the bad API token rather than reporting that the specified app wasn't found.

**Comment by tomachi** [comment]
The same happened here. Still fighting with it. Would be nice to know the real cause, as today it's pointing to an endless error message.

**Comment by ishadua04** [comment]
Faced the same error message and the refreshing the token worked. The error message is quite misleading.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
