### ISSUE TITLE
Support for iOS fastlane deliver attribute: app_version for appcenter_upload action

### ISSUE THREAD

**Issue by ggallotti** [microsoft/fastlane-plugin-appcenter#234]
Add support for fastlane deliver app_version attribute in the appcenter_upload fastlane action. 

https://docs.fastlane.tools/actions/deliver/
`app_version | The version that should be edited or created`

**Why?**
In order to be able to specify the app version name that will be shown in the Apple store for the Released version

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
