### ISSUE TITLE
appcenter_upload requests to "Select OS" and fails anyway when attempting to upload to new bucket

### ISSUE THREAD

**Issue by JWShroyer** [microsoft/fastlane-plugin-appcenter#237]
I'm using Fastlane.swift with this plugin enabled to distribute apps to AppCenter. When I created a new bucket to distribute apps to for the organization I work for, I cannot distribute builds to that bucket. I've set it up to be an iOS bucket on AppCenter and I am providing `ios` as the app platform (I have also tried `iOS`) using the plugin, but I'm still asked for the platform. I've checked to confirm the app name is correct given the URL and the destination name I'm providing matches the name of the distribution group (as found in the settings of the distribution group).

This is what is printing in my terminal when providing the `--verbose` command.

```
DEBUG [2020-07-21 16:30:26.92]: received command:#<Fastlane::ActionCommand:0x00007fd6b153f608 @method_name="appcenter_upload", @class_name=nil, @command_id="", @args=[named argument: api_token, value: {redacted}, type: , named argument: owner_type, value: organization, type: , named argument: owner_name, value: {redacted}, type: , named argument: app_name, value: {redacted, but found in URL of bucket}, type: , named argument: app_platform, value: ios, type: , named argument: destinations, value: {redacted, but found in settings of Distribution Group}, type: , named argument: destination_type, value: group, type: , named argument: mandatory_update, value: false, type: , named argument: notify_testers, value: true, type: , named argument: release_notes, value: My notes, type: , named argument: should_clip, value: true, type: ]>
```
I am then presented with the following prompt:
```
INFO [2020-07-21 16:30:26.92]: ------------------------------
INFO [2020-07-21 16:30:26.92]: --- Step: appcenter_upload ---
INFO [2020-07-21 16:30:26.92]: ------------------------------
WARN [2020-07-21 16:30:27.40]: Select OS
1. Android
2. iOS
3. macOS
4. Windows
5. Custom
?
```

Even when provided, the script continues, but this error message is printed:

```
Error creating app 400: {"error"=>{"code"=>"BadRequest", "message"=>"Validation error for body parameter \"app.platform\": No enum match for: ios"}}
```

### Versions
fastlane-plugin-appcenter: 1.9.0
Fastlane: 2.152.0
Bundler: 2.1.4
ruby: 2.6.5
rbenv: 1.1.2
macOS: 10.15.6
Xcode: 11.6 (11E708)

## Update:

I was able to get things working by removing the `app_platform` parameter and instead trying to rely on it knowing this value based on what's being uploaded and what AppCenter is defined to use. This helped shed light on a suspicion I had that it couldn't find the new bucket for some reason and this was verified. I was presented with something stating it couldn't find the bucket with the name I specified and asked if I wanted to create it. I decided to say yes and see where the prompts were taking me. Unfortunately it couldn't create it because of a `409` error due to a `Conflict` when attempting to create the new bucket (probably because it already existed but couldn't find it). 

Ultimately I deleted the bucket from AppCenter and ran the script again. It was able to successfully create the bucket this time because there was no conflict and now all future uploads are working as expected. 

Leaving this issue here though because of the problem I ran into. Just providing a workaround for anyone with a similar issue.

**Comment by anywherepilot** [comment]
Hi @JWShroyer.  I think you are confusing `platform` with `os`. Please visit https://openapi.appcenter.ms and search for `AppRequest`, which is part of the body sent to the `/apps` endpoint in the `POST` request creating an app. There you can see the list (`enum`) of accepted values for `platform`. The value you mention, `ios`, is an operating system and you should pass it as `os`. Then set the `platform` to in your case I guess `Objective-C-Swift`.

**Comment by JWShroyer** [comment]
Thanks, @anywherepilot. I think you're absolutely right. But what about the part where I removed that entirely and it asked to create a new app and failed to do so with a `409 Conflict`? I'm definitely not opposed to closing this issue. I just want to make sure this part in particular is looked at if possible.

**Comment by jp-andre** [comment]
I believe this issue is similar to #151

**Comment by JWShroyer** [comment]
@jp-andre should I close this if the other issue is similar?

**Comment by jp-andre** [comment]
Honestly, I'm not sure about `409 Conflict` but it could be because it can take a while for a deletion to propagate through our databases.

In my understanding the remaining issue is as follows:
- create an app automatically
- upload fails
Which is what happens with #151. So I will close this.
