### ISSUE TITLE
Not found, invalid distribution group name

### ISSUE THREAD

**Issue by olegmyatlikov** [microsoft/fastlane-plugin-appcenter#240]
The plugin can't find group distribution group name when I trying to upload build. I get warning "Not found, invalid distribution group name P97 Developer/Tester" but I'm sure the group exists. And more when I fetching devices with method appcenter_fetch_devices everything works fine. 

```ruby
  appcenter_upload(
    api_token: "some token",
    owner_name: "some owner",
    owner_type: "organization",
    app_name: "some name",
    file: "./Some App.ipa",
    upload_build_only: true,
    destinations: "Developer/Tester",
    notify_testers: false
  )

  appcenter_fetch_devices(
    api_token: "some token",
    owner_name: "some owner",
    app_name: "some name",
    destinations: "Developer/Tester",
    devices_file: "devices.txt"
  )
```

**Comment by anywherepilot** [comment]
Does it work with group names which don't have a slash their name?

**Comment by olegmyatlikov** [comment]
When I changed name to "Developer and Tester" I got this error:

...
[14:35:52]: --- Step: appcenter_upload ---
[14:35:52]: ------------------------------
[14:35:54]: Error adding app to distribution group 403: {"message"=>"A app API token cannot be used to make requests to this endpoint. Please use a user API token.", "statusCode"=>403, "code"=>"Forbidden"}
[14:35:54]: Starting release upload...
[14:35:55]: Setting Metadata...
[14:35:56]: Metadata set
[14:35:56]: Uploading release binary...
[14:36:00]: Chunk uploaded
...

Build uploaded but without selected group

**Comment by olegmyatlikov** [comment]
issue was resolved when I changed API Token from app token to user token. I think it should be added to documentation.

**Comment by jarnove** [comment]
I tried both tokens, but without any results, any ideas? Is this already added to the documentation?

**Comment by francescopedronomnys** [comment]
> issue was resolved when I changed API Token from app token to user token.
@olegmyatlikov what are you referring to? I have the same problem but I don't know how to make the change you are referring to.
Thanks
