### ISSUE TITLE
Errno::ENOENT: No such file or directory - appcenter

### ISSUE THREAD

**Issue by spacesuitdiver** [microsoft/fastlane-plugin-appcenter#253]
Is appcenter-cli required as a global? I would gladly open a PR to clarify this in the README if so. Thanks!

**Comment by jp-andre** [comment]
No, it isn't.

**Comment by spacesuitdiver** [comment]
I'm not finding this to be true. I end up running on our build boxes.
```
echo "Installing appcenter for Fastlane plugin..."
npm install -g appcenter-cli || exit 1
```

**Comment by spacesuitdiver** [comment]
Disregard, this is codepush we are doing sorry 

https://github.com/microsoft/fastlane-plugin-appcenter/blob/fb13cc9633e7e6fae863c027e051e0a9c2f4d766/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb#L63

Clearly shows it is uploading directly via api.
