### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by tpucci** [microsoft/fastlane-plugin-appcenter#256]
Hi there!

We detected an issue with `appcenter_upload` lane.

```js
[13:20:30]: ------------------------------
[13:20:30]: --- Step: appcenter_upload ---
[13:20:30]: ------------------------------
[13:20:31]: Starting release upload...
+-------------------------------------+--------------------------------------------------------------------------------+
|                                                     Lane Context                                                     |
+-------------------------------------+--------------------------------------------------------------------------------+
| ENVIRONMENT                         | staging                                                                        |
| PLATFORM_NAME                       |                                                                                |
| LANE_NAME                           | distribute                                                                     |
| GRADLE_ALL_APK_OUTPUT_PATHS         | ["/bitrise/src/app/build/outputs/apk/staging/release/app-staging-release.apk"] |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | []                                                                             |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                                             |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | ["/bitrise/src/app/build/outputs/mapping/stagingRelease/mapping.txt"]          |
| GRADLE_APK_OUTPUT_PATH              | /bitrise/src/app/build/outputs/apk/staging/release/app-staging-release.apk     |
| GRADLE_MAPPING_TXT_OUTPUT_PATH      | /bitrise/src/app/build/outputs/mapping/stagingRelease/mapping.txt              |
+-------------------------------------+--------------------------------------------------------------------------------+
[13:20:31]: Internal Service Error, please try again later

```
```js

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+

.....

| 💥   | appcenter_upload                                              | 0           |
+------+---------------------------------------------------------------+-------------+
```

Can you confirm there is an issue on your side?

We don't see any issue on https://status.appcenter.ms. However, some other people are also facing the issue (https://github.com/microsoft/fastlane-plugin-appcenter/issues/182#issuecomment-740573539).

**Comment by metalsong** [comment]
Maybe it relates to App Center CLI update that microsoft performed today.

**Comment by marudy** [comment]
I can confirm that i see this periodically since Friday/Saturday last week - December 4th,5th. On Sunday it was working again

**Comment by falcon4ever** [comment]
No sure if it's related but this morning (EST) my builds just get stuck while trying to upload. No errors or time-out at all

`[09:08:23]: ------------------------------
[09:08:23]: --- Step: appcenter_upload ---
[09:08:23]: ------------------------------
[09:08:24]: Starting release upload...
[09:08:30]: Setting Metadata...
[09:08:30]: Metadata set
[09:08:30]: Uploading release binary...
[09:08:31]: Chunk uploaded
[09:08:31]: Chunk uploaded
[09:08:32]: Chunk uploaded
[09:08:33]: Chunk uploaded
[09:08:34]: Chunk uploaded
[09:08:34]: Chunk uploaded
[09:08:35]: Chunk uploaded
[09:08:36]: Chunk uploaded
[09:08:37]: Chunk uploaded
[09:08:37]: Binary uploaded
[09:08:37]: Finishing release...
[09:08:37]: Upload finished
[09:08:39]: Waiting for release to be ready...
`

It was working fine for us yesterday.

**Comment by marudy** [comment]
As I said i'm experiencing this issue since the weekend. My plugin version is `1.8.0`. Today I tried to upgrade to version `1.11.0` and i am getting the same error as @falcon4ever but fastlane times out eventually. Trying also with `1.10.0` to see if anything changes.

**Comment by david-mora-cs** [comment]
Having the same "Internal Service Error, please try again later" issue.

**Comment by IronLeash** [comment]
I'm also stuck at "Waiting for release to be ready..." with the version. 1.11.0.
Previously I was on 1.9.0 that was returning me 
Client error: 400: {“error”=>{“code”=>400, “message”=>“The request contains invalid content.“}}.
I don't think that the error is related with the plugin, I seems so that app center has an internal issue.

**Comment by alexandrst88** [comment]
```Past Incidents
Dec 8, 2020
App Center CLI Upgrade Required to Continue Using Distribution
Completed - The scheduled maintenance has been completed. 
Dec 8, 04:20 UTC
In progress - Scheduled maintenance is currently in progress. We will provide updates as necessary. 
Dec 7, 22:20 UTC
Scheduled - The `appcenter distribute release` command in App Center CLI versions prior to v2.7.0 has stopped functioning as per our earlier communications (related to the HockeyApp SDK shutdown communicated earlier, as the old API depends on a HockeyApp proxy). To continue using the App Center distribution capability from the CLI, please upgrade your CLI to the latest version (v2.7.0 or above). You can upgrade the Appcenter CLI by running the following command in your terminal/command prompt: `npm i -g appcenter-cli`.

Also, if you are using custom scripts with our swagger API, please adjust your script based off the implementation of App Center CLI.

To get more information on CLI installation, refer to App Center CLI GitHub repo. As always, if you have any questions or need any assistance, feel free to reach out to us via support. Thank you! 
Dec 7, 22:19 UTC```

https://status.appcenter.ms/#past-incidents

**Comment by kabirkhaan** [comment]
I am also facing the same issue, **Waiting for release to be ready...** taking way too long.

```
14:54:36]: ------------------------------
[14:54:36]: --- Step: appcenter_upload ---
[14:54:36]: ------------------------------
[14:54:37]: Starting release upload...
[14:54:39]: Setting Metadata...
[14:54:41]: Metadata set
[14:54:41]: Uploading release binary...
[14:54:43]: Chunk uploaded
[14:54:44]: Chunk uploaded
[14:54:46]: Chunk uploaded
[14:54:47]: Chunk uploaded
[14:54:49]: Chunk uploaded
[14:54:50]: Chunk uploaded
[14:54:51]: Chunk uploaded
[14:54:53]: Chunk uploaded
[14:54:54]: Chunk uploaded
[14:54:56]: Chunk uploaded
[14:54:57]: Chunk uploaded
[14:54:58]: Chunk uploaded
[14:54:58]: Binary uploaded
[14:54:58]: Finishing release...
[14:54:59]: Upload finished
[14:54:59]: Waiting for release to be ready...
[15:12:04]: Error fetching information about release 502: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.15.10</center>
</body>
</html>
```

**Comment by djbrooks111** [comment]
Likewise with us, just updated to `1.10.0` and fastlane `2.170.0`. However, we received a 504:
```
[09:04:29]: ------------------------------
[09:04:29]: --- Step: appcenter_upload ---
[09:04:29]: ------------------------------
[09:04:36]: Starting release upload...
[09:04:37]: Setting Metadata...
[09:04:37]: Metadata set
[09:04:37]: Uploading release binary...
[09:04:37]: Chunk uploaded
[09:04:38]: Chunk uploaded
[09:04:39]: Chunk uploaded
[09:04:40]: Chunk uploaded
[09:04:40]: Chunk uploaded
[09:04:41]: Chunk uploaded
[09:04:42]: Chunk uploaded
[09:04:42]: Chunk uploaded
[09:04:43]: Chunk uploaded
[09:04:44]: Chunk uploaded
[09:04:45]: Chunk uploaded
[09:04:45]: Chunk uploaded
[09:04:46]: Chunk uploaded
[09:04:46]: Binary uploaded
[09:04:46]: Finishing release...
[09:04:46]: Upload finished
[09:04:47]: Waiting for release to be ready...
[09:11:47]: Error fetching information about release 504: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.10</center>
</body>
</html>
```

**Comment by niparx** [comment]
We have same issues.
Waiting, when it will be resolved with new plugin update.

**Comment by andreashanft** [comment]
Same issue here as well. Just updated to `fastlane-plugin-appcenter 1.11.0` and `fastlane 2.170.0` as upload was failing due to recent CLI changes of App Center. Now our builds are stuck for 30+ mins on

```
Waiting for release to be ready...
```

and either eventually succeed or fail with 

```
Error fetching information about release 502: <html>
16:10:42  <head><title>502 Bad Gateway</title></head>
16:10:42  <body>
16:10:42  <center><h1>502 Bad Gateway</h1></center>
16:10:42  <hr><center>nginx/1.15.10</center>
16:10:42  </body>
16:10:42  </html>
```

**Comment by jonhocking** [comment]
Likewise also experiencing this issue. I was seeing a failure with version `1.8.0` and so updated to `1.11.0` and  now I se the same `Waiting for release to be ready…` timeout

**Comment by michaelcarrano** [comment]
Experiencing the same issue as everyone else. 

What I noticed is that app does get uploaded to AppCenter but there are no `destinations` set. So in the meantime, I am manually setting the destination for builds on the website. However, this means our CI will continue to report the jobs as failed.

**Comment by innocarpe** [comment]
We have same issues too. `fastlane 2.170.0` / `fastlane-plugin-appcenter 1.11.0`

**Comment by KevinWellsBokf** [comment]
My team is also experiencing this as of today.

This morning we were using: fastlane (2.154.0) / fastlane-plugin-appcenter (1.9.0)
I noticed our builds failing in CI. At this point our builds were making it onto App Center, but the deployment process was failing with a '504 Gateway Time-out', as seen by @michaelcarrano above.
I read the App Center incident mandating a CLI update and then updated our fastlane App Center plugin.

Now we are using: fastlane (2.170.0) / fastlane-plugin-appcenter (1.11.0)
After updating, the App Center plugin's deployment step is stuck on 'Waiting for release to be ready...' for ten minutes, at which point my CI/CD provider kills the build. In this case the App Center upload does not complete, and no build shows up on App Center.

**Comment by Kbotei** [comment]
Experiencing the same thing here with fastlane 2.170.0 and fastlane-plugin -appcenter 1.11.0. I also tried a manual upload via the appcenter.ms website and it timed out as well.

**Comment by kchasiotis** [comment]
We are facing the same issue too. May god have mercy upon our souls!

**Comment by pimJNGNL** [comment]
facing the same issue!

**Comment by Almouro** [comment]
It now seems to be under investigation https://status.appcenter.ms/ 🤞 

![image](https://user-images.githubusercontent.com/4534323/101518110-c397c500-3981-11eb-8055-a3995f756f0c.png)

**Comment by shepting** [comment]
And it's back for us! Everything is working again.

**Comment by grndvl1** [comment]
Also their openapi is messed up for this the json we get back now is this 
`UPLOAD JSON = [{"code":"internal_server_error","message":"internal error (Support ID: 9f217d73-598d-4750-811b-639dab4aafcf)"}]`
used to work on Friday but Monday I get the above.  The gave me some canned response about CLI but I don't use CLI we use the openapi url endpoints.  Wish they would stop messing with this, this is the 4th time I had to fix something this year because of their upgrades!

**Comment by michaeldwilliams** [comment]
This is the seemingly canned answer AppCenter support gave me but I'm not sure this is the answer.

> The distribution services REST API is deprecated as per our earlier announcement, release_uploads endpoints have stopped functioning.
> 
> To continue using the Distribute services, please see the alternatives below:
> ·         Release with the App Center CLI (v2.7.0 or above) - https://docs.microsoft.com/en-us/appcenter/distribution/uploading#distributing-using-the-app-center-command-line-interface You can upgrade Appcenter CLI by running the following command in your terminal/command prompt: npm i -g appcenter-cli. 
>
> ·         If you are using custom scripts with our swagger API, adjust your API script based off the implementation of App Center CLI. To get more information on CLI installation, refer to App Center CLI GitHub repo. 
>
> ·         Or you may also upload the releases via our web portal or with our Build service.For more information please see here: https://status.appcenter.ms/incidents/4nbhlm0lxsvt
> 
> Thanks,App Center team
> 
> 
>

**Comment by michaeldwilliams** [comment]
Follow up email from support:

> we were experiencing issues earlier with our distribution service but our team has deployed a fix. The latest version of Fastlane plugin should work now.

**Comment by andresfcamacho** [comment]
Still not working for us. Fastlane 2.133.0 and fastlane-plugin -appcenter 1.11.0. 

```
22:19:30]: ------------------------------
[22:19:30]: --- Step: appcenter_upload ---
[22:19:30]: ------------------------------
[22:19:30]: Starting release upload...
[22:19:30]: Error 410: {"code"=>"gone", "message"=>"This API is deprecated. Please use the latest version of the App Center CLI: https://github.com/microsoft/appcenter-cli, or if you need a custom script please use the CLI as the basis for your implementation. (Support ID: eacb7702-00c4-4bbb-ab15-e5ef7972a507)"}
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
```

**Comment by rpassis** [comment]
@andresfcamacho The latest version of the AppCenter plugin is `1.11.0`, have you tried updating it?

**Comment by david-mora-cs** [comment]
We were able to make it work recently for us by:
`bundle install`
`bundle update fastlane`
`bundle exec fastlane update_plugins`

**Comment by tpucci** [comment]
Closing the issue: AppCenter plugin version `1.11.0` fixes the issue. Thanks!

➡️ Update your plugins with `bundle exec fastlane update_plugins`.
