### ISSUE TITLE
No Android Instructions

### ISSUE THREAD

**Issue by grndvl1** [microsoft/fastlane-plugin-appcenter#258]
Building on CircleCI and for android.  This says its for android but there are no instructions on what do for android and if you are using a remote builder and pushing to Appcenter or some other developer store.

**Comment by DmitriyKirakosyan** [comment]
Hi @grndvl1 , sorry for late reply.
Could you add more details on what instructions exactly you are looking for?
You can find the detailed documentation of fastlane-plugin-appcenter usage on the github main page.
Please let me know if anything is missing in Readme.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
