### ISSUE TITLE
Return release_url as output or add to SharedValues

### ISSUE THREAD

**Issue by Tayphoon** [microsoft/fastlane-plugin-appcenter#259]
We would like to parse release url link in our CI to be ease find build related to current job.

**Comment by davevdveen** [comment]
Maybe you already found out but this is already possible if you directly call `Helper::AppcenterHelper.get_release_url`. The only extra parameter you need is the `release_id` which can be retrieved from `APPCENTER_BUILD_INFORMATION`.

```
api_token = ""
owner_type = ""
owner_name = ""
app_name = ""
commit_message = ""
  
appcenter_upload(
    api_token: api_token,
    owner_type: owner_type,
    owner_name: owner_name,
    app_name: app_name,
    release_notes: commit_message,
    file: ipa_file,
  )
  
build_information = lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]
release_id = build_information['id']
release_url = Helper::AppcenterHelper.get_release_url(owner_type, owner_name, app_name, release_id)
```

**Comment by DmitriyKirakosyan** [comment]
Hi @Tayphoon , can you confirm that https://github.com/microsoft/fastlane-plugin-appcenter/issues/259#issuecomment-930893532 works for you?
Also release url is printed after it is uploaded, see https://github.com/microsoft/fastlane-plugin-appcenter/blob/master/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L231.

Closing this feature request, but feel free to reopen if you have additional questions.

**Comment by DmitriyKirakosyan** [comment]
Hi @matt-dalton , yes, `get_install_url` returns the base page with list of releases.
Have you tried building the url manually by adding `/releases/{release_id}` to the result of `get_install_url`? You can get `release_id` from the release url.

**Comment by matt-dalton** [comment]
Gotcha - yeah did something similar as a workaround. Was wondering if there was an in-built way of doing it. Thanks.

**Comment by DmitriyKirakosyan** [comment]
@matt-dalton , No built-in way, but a contribution is very welcome :)
