### ISSUE TITLE
Code push support

### ISSUE THREAD

**Issue by Belobobr** [Microsoft/fastlane-plugin-appcenter#26]
Do you support updates thought code push service? Have you any plans on this?

**Comment by janpio** [comment]
These exist:
https://github.com/j2kun/fastlane-codepush
https://github.com/manuelkch/fastlane-plugin-code_push (for react native)

Don't know how good they are though.

**Comment by Amurmurmur** [comment]
@janpio those plugins dont support appcenter codepush

**Comment by Pranit-Harekar** [comment]
Please use this CodePush plugin: https://github.com/Pranit-Harekar/fastlane-plugin-codepush
