### ISSUE TITLE
Feature: Make "release_notes" available on the output of "appcenter_fetch_version_number" or create new "appcenter_fetch_latest_release"

### ISSUE THREAD

**Issue by yinzara** [microsoft/fastlane-plugin-appcenter#260]
The "appcenter_fetch_version_number" lane, though it is used to fetch the current version of the app, really does a lot more than that.   It finds the most recent release of an application and returns a limited bit of information about it.

My team currently uses "release_notes" of an appcenter release to store a hash of the source of the built application for comparison during our autobuild process.

It would be helpful if "appcenter_fetch_version_number" also returned the "release_notes" of that version so we could use it in our build (otherwise we're forced to use the appcenter cli).

An alternative solution would be a new "appcenter_fetch_latest_release" (or similar) that returned all fields of the latest.

I am willing to implement this feature.

**Comment by DmitriyKirakosyan** [comment]
Hi @yinzara , sorry for late reply and thank you for the feature request.

> I am willing to implement this feature.

Contributions are very welcome, so if you are still interested, please do it :)

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
