### ISSUE TITLE
Feature: ability to use AppCenter App "app_secret" during the build process

### ISSUE THREAD

**Issue by yinzara** [microsoft/fastlane-plugin-appcenter#261]
Each app in AppCenter has an system generated "app_secret".   This secret is required when your application is built as it needs to be embedded inside the build package to use app center functionality with the app.

I have two problems
1. If there is no app currently and I want to create one, the only way to do that is by uploading a release. But because I need the app_secret to create the release. I'm in a chicken and egg situation. I need a way to create an app in AppCenter and get the app_secret from it before I upload the release.
2. Even if I'm in a more traditional workflow and the app already exists, there is no method currently to retrieve the app_secret for for a given app by app_name.  I need a method to retrieve the app_secret from an app by the same attributes I use in `appcenter_fetch_version_number`

**Comment by DmitriyKirakosyan** [comment]
Hi @yinzara , sorry for late reply.

App Secret is used for AppCenter SDK integration and sending data to app center. It is not required for uploading a release.
Could you please tell more about your case? How exactly would you use app secret in your automation process?

**Comment by hostmasterpontuax** [comment]
Hi @DmitriyKirakosyan.

I have a need to get the App Secret in build phase.
As I have a whitelabel project, for each app I would need to store the App Secret separatedly or just fetch it using a action from this plugin.

It would help a lot if we could get the App Secret with this plugin.

**Comment by yinzara** [comment]
I create apps with every feature branch of my application.  I don't just create it on app center then store the app secret. To do that I need a way of creating an app and then retrieving the app secret. Hence my feature request.  The app secret is also used in the build process if you have app center sdk in your app.

**Comment by DmitriyKirakosyan** [comment]
AppCenter fastlane plugin doesn't provide an option for retrieving an app secret. To get an app secret you can use `appcenter-cli`:

- **For existing app**
  Using command `appcenter apps show`, eg:
  ```bash
  appcenter apps show --token <token> --app <app-owner/<app-name> | grep "App Secret" | sed 's/App Secret: *//'
  ```

- **For new app**
  Using command `appcenter apps create`, eg:
  ```bash
  appcenter apps create --token <token> --platform Java --os Android --name <app-name> -d <app-display-name>
  ```
  and parse the output for the "App Secret" property.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue, but feel free to ask additional questions.

**Comment by yinzara** [comment]
There is plenty of functionality the app center cli can do that this plugin also does.  Why is that justification that the plugin shouldn't do that?

**Comment by DmitriyKirakosyan** [comment]
@yinzara , this plugin designed to do only a limited number of actions:

- appcenter_fetch_devices
- appcenter_upload
- appcenter_fetch_version_number
- appcenter_codepush_release_react

While `appcenter-cli` is wrapping the [App Center Open API](https://openapi.appcenter.ms/) and allows to perform full range of actions.

Can you clarify why using `appcenter-cli` is not an option for you?
