### ISSUE TITLE
android 11 target apk upload is failing even when uploaded manually

### ISSUE THREAD

**Issue by NavalKishor** [microsoft/fastlane-plugin-appcenter#264]
Steps to reproduce 
1. prepare an app with this config in build.gradle(app)
`` minSdkVersion = 30
 `` targetSdkVersion = 30
  `` compileSdkVersion = 30
and use this config in gradle and prepare a normal apk and upload it manually app will through error 
`A problem occured while extracting your app. (Correlation ID: 8e0647ef-215c-4f20-bde6-239cb969624d)`
and upload will fail.
i have extracted the apk and check the AndroidManifest.xml and its highly obfuscated no info about the above info or package details and below apk will show 

but when i am using 
aapt dumb badging myapp.apk 
its showing all the details info present in AndroidManifest.xml

**Comment by DmitriyKirakosyan** [comment]
Hi @NavalKishor , sorry for late reply. If you face the same issue when uploading the apk manually, then it is not a fastlane plugin issue. Please reach out to the [AppCenter support](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) team by pressing the question mark (?) on the appcenter.ms page.

I'm closing this issue but feel free to reopen if you have additional questions.
