### ISSUE TITLE
Upload DSYM without building the project

### ISSUE THREAD

**Issue by garrefa** [microsoft/fastlane-plugin-appcenter#265]
Hi, I cant find a way to just upload a dsym file without the plugin starting to build the project.
In case I already have the dsym at hand, why is the build necessary? How can I prevent it?

Thanks

**Comment by DmitriyKirakosyan** [comment]
Hi @garrefa , have you tried `upload_dsym_only: true` option?
See example here: https://github.com/microsoft/fastlane-plugin-appcenter/blob/master/fastlane/Fastfile#L127.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
