### ISSUE TITLE
Plugin doesn't support Android Gradle Plugin 4.1.0+

### ISSUE THREAD

**Issue by nisrulz** [microsoft/fastlane-plugin-appcenter#266]
Android Gradle plugin got rid of BuildConfig property named `VERSION_NAME`and `VERSION_CODE`. That means when we upgrade AGP to v 4.1.0+ in the stable channel, we get a lot of errors like below:
```
Unresolved reference: VERSION_NAME
```

In order to solve it, one needs to replace those fields with a custom defined fields like below:

```
  buildConfigField 'int', 'VERSION_CODE', "1"
  buildConfigField 'String', 'VERSION_NAME', "\"1.0\""

```

Read solution notes: https://commonsware.com/blog/2020/10/14/android-studio-4p1-library-modules-version-code.html

Read more about it: https://developer.android.com/studio/releases/gradle-plugin#version_properties_removed_from_buildconfig_class_in_library_projects

Now, that said when following the above solution and also using `appcenter` plugin via fastlane, I get the following error when using `appcenter_upload` action:
```
Error fetching release: A problem occurred while extracting your app. (Correlation ID: some-id)
```
> Possibly relates to #243 

I have tried to get logs via `--verbose` flag but there is nothing odd to be found. 

So I kept everything as it is  and just reverted to older Android Gradle Plugin(AGP) version 4.0.2 and using the base `versionName` and `versionName` from the AGP. 
When I rerun the action `appcenter_upload` everything goes through successfully.

So from these steps, it became clear the fastlane plugin is having trouble finding the `versionName` and `versionCode` fields once they are removed in AGP 4.1.0+. 

I did try to look into the source code to find any such reference, but couldn't find anything.

I would be happy to contribute, but would need some pointers. :)

**Comment by nisrulz** [comment]
Hello, I hate to ask, but was hoping for an update on this. Even some context, to allow working in a fork would be helpful.

**Comment by DmitriyKirakosyan** [comment]
Hi @nisrulz , sorry for late reply. Are you still experiencing this issue?

**Comment by nisrulz** [comment]
Yes, but based on my conversation with the Appcenter support team over email I was told to switch my implementation to use AppCenter CLI. The CLI is well maintained vs this plugin. Also is decoupled from AGP.

**Comment by DmitriyKirakosyan** [comment]
Glad to hear you found a way to get it working. Does it mean you're not interested in this feature anymore?

**Comment by nisrulz** [comment]
I would say that the feature is critical for this plugin as a project. However for my usecase I do not use this plugin anymore.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
