### ISSUE TITLE
Plugin doesn't add build to distribution group

### ISSUE THREAD

**Issue by kemalenver** [microsoft/fastlane-plugin-appcenter#267]
I have the following function.  When it runs, the app is created on AppCenter, but my destinations are only set to Collaborator.  I set destinations to * so I thought I'd see the app added to my other distribution groups.  

```
appcenter_upload(
			api_token: ENV["APP_CENTER_API_TOKEN"],
			owner_name: "XXXX",
			owner_type: "organization",
			app_os: "iOS",
			app_platform: "Objective-C-Swift",
			app_display_name: "special-build",
			app_name: "special-build",
			file: "../XXXX.ipa",
			notify_testers: false,
			destinations: "*"
		)
```

**Comment by simon-videoloft** [comment]
Same issue here. Seems to be working fine for the 'user' owner_type, just not 'organisation'.

**Comment by kemalenver** [comment]
FYI If I set a destination name directly it works - it's just the wildcard that doesn't.

**Comment by JWShroyer** [comment]
Hey! Seems like this thread is a little sleepy. My team just started looking into transitioning to AppCenter for our In House distribution and testing and we're also seeing the same issue as outlined here. 

We are using `fastlane-plugin-appcenter (1.11.1)`

**Comment by DmitriyKirakosyan** [comment]
Hi folks, this issue seems to be fixed already. I've checked `destinations: "*"` for user level app and organization level app, and it worked as expected for me.

Can you confirm that you are not facing this issue anymore?

**Comment by DmitriyKirakosyan** [comment]
I'm closing this item but feel free to reopen if anyone still faces the issue.
