### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by bboles** [microsoft/fastlane-plugin-appcenter#269]
Can anyone comment on whether Microsoft is still supporting the plugin?  There hasn't been any new code commits in over 6 months and the last closed issue was nearly 5 months ago.

**Comment by DmitriyKirakosyan** [comment]
Hi @bboles , thank you for reaching out!

We support this plugin, however we don't actively work on adding features due to other priorities.
See [AppCenter Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap).

**Comment by bboles** [comment]
Thank you for the update @DmitriyKirakosyan !
