### ISSUE TITLE
Upload failed! Internal Service Error, please try again later

### ISSUE THREAD

**Issue by ir2pid** [microsoft/fastlane-plugin-appcenter#270]
Getting this error since today for both ios and android

![image](https://user-images.githubusercontent.com/907075/115404343-8a077e00-a1ed-11eb-9e27-4606d2f2b66e.png)

**Comment by DmitriyKirakosyan** [comment]
Hi @ir2pid , are you still facing this issue?

**Comment by PlugFox** [comment]
![image](https://user-images.githubusercontent.com/7805176/198593694-c70ae784-585f-46e8-8d96-257a3a2692c7.png)

Have the same problem

**Comment by PlugFox** [comment]
> Hi @PlugFox, there was an outage of processing release upload requests on our side this day but for now this issue has been resolved. Could you please try again?

Yeap, it's working for me.

I think is good idea to add more information to error or display stacktrace

**Comment by MikhailSuendukov** [comment]
@PlugFox Thank you for contacting us. I close this issue.
