### ISSUE TITLE
Problem occurred while extracting your app

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/fastlane-plugin-appcenter#276]
I am trying to upload a WinUI desktop package in appcenter, but i am facing a below issue when uploading the packages.

![image](https://user-images.githubusercontent.com/56436173/129879596-29f58db4-ab94-4b26-b51f-e5a49586e305.png)

In addition, I have tried some other app create options, all the way leads to the same error.

Can you please tell how to publish winui desktop (.msixbundle or zipped .msixbunde) in app center?

Also, please suggest which option to choose for WinUI Desktop app publishing? 

![image](https://user-images.githubusercontent.com/56436173/129879918-5c7f350c-513a-42c6-8cf9-e510dd419fde.png)

**Note:** I have already published the WinUI UWP app in app center, must publish a WinUI desktop package.

**Comment by DmitriyKirakosyan** [comment]
Hi @KanniyappanP , sorry for late reply. If you are still experiencing this issue, please reach out to the [App Center support](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) team by pressing the question mark (?) button on the appcenter.ms portal.

I'm closing this issue as it is not related to the fastlane plugin.
