### ISSUE TITLE
A problem occured while extracting your app

### ISSUE THREAD

**Issue by saaaab1213** [microsoft/fastlane-plugin-appcenter#278]
I am experiencing this issue when uploading to appCenter an iOs distribution from CircleCI. When executing fastlane on local machines it works completely fine all of the times and everything works fine, but on CI it throws an error. After a week of tests I don't know where the problem might be

**INFO [2021-09-17 10:49:17.50]: Waiting for release to be ready...
ERROR [2021-09-17 10:49:43.24]: Error fetching release: A problem occured while extracting your app. (Correlation ID: 7afd1e19-5769-45e7-a915-2be7d1a98057)**

INFO [2021-09-17 10:49:06.99]: ▸   adding: yoga.framework.dSYM/Contents/Info.plist (deflated 52%)

INFO [2021-09-17 10:49:06.99]: Successfully exported and compressed dSYM file
INFO [2021-09-17 10:49:06.99]: Successfully exported and signed the ipa file:
INFO [2021-09-17 10:49:06.99]: /Users/distiller/project/ios/MyAPPTest.ipa
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
INFO [2021-09-17 10:49:07.03]: ------------------------------------------
INFO [2021-09-17 10:49:07.03]: --- Step: Switch to ios appcenter lane ---
INFO [2021-09-17 10:49:07.03]: ------------------------------------------
INFO [2021-09-17 10:49:07.03]: Cruising over to lane 'ios appcenter' 🚖
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
INFO [2021-09-17 10:49:07.05]: ------------------------------
INFO [2021-09-17 10:49:07.05]: --- Step: appcenter_upload ---
INFO [2021-09-17 10:49:07.05]: ------------------------------
INFO [2021-09-17 10:49:07.53]: Starting release upload...
INFO [2021-09-17 10:49:07.89]: Setting Metadata...
INFO [2021-09-17 10:49:08.25]: Metadata set
INFO [2021-09-17 10:49:08.25]: Uploading release binary...
INFO [2021-09-17 10:49:08.95]: Chunk uploaded
INFO [2021-09-17 10:49:09.64]: Chunk uploaded
INFO [2021-09-17 10:49:10.46]: Chunk uploaded
INFO [2021-09-17 10:49:11.08]: Chunk uploaded
INFO [2021-09-17 10:49:11.72]: Chunk uploaded
INFO [2021-09-17 10:49:12.41]: Chunk uploaded
INFO [2021-09-17 10:49:13.21]: Chunk uploaded
INFO [2021-09-17 10:49:14.06]: Chunk uploaded
INFO [2021-09-17 10:49:14.80]: Chunk uploaded
INFO [2021-09-17 10:49:15.42]: Chunk uploaded
INFO [2021-09-17 10:49:16.14]: Chunk uploaded
INFO [2021-09-17 10:49:16.75]: Chunk uploaded
INFO [2021-09-17 10:49:17.16]: Chunk uploaded
INFO [2021-09-17 10:49:17.16]: Binary uploaded
INFO [2021-09-17 10:49:17.16]: Finishing release...
INFO [2021-09-17 10:49:17.33]: Upload finished
INFO [2021-09-17 10:49:17.50]: Waiting for release to be ready...
ERROR [2021-09-17 10:49:43.24]: Error fetching release: A problem occured while extracting your app. (Correlation ID: 7afd1e19-5769-45e7-a915-2be7d1a98057)
WARN [2021-09-17 10:49:43.24]: Lane Context:
INFO [2021-09-17 10:49:43.24]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test", :KEYCHAIN_PATH=>"~/Library/Keychains/fastlane_tmp_keychain", :ORIGINAL_DEFAULT_KEYCHAIN=>"\"/Users/distiller/Library/Keychains/login.keychain-db\"", :SIGH_PROFILE_TYPE=>"ad-hoc", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"com.*******.****.app.test"=>"com.*******.****.app.test AdHoc"}, :IPA_OUTPUT_PATH=>"/Users/distiller/project/ios/MyAPPTest.ipa", :XCODEBUILD_ARCHIVE=>"/Users/distiller/Library/Developer/Xcode/Archives/2021-09-17/MyAPPTest 2021-09-17 10.20.57.xcarchive", :DSYM_OUTPUT_PATH=>"/Users/distiller/project/ios/MyAPPTest.app.dSYM.zip"}
ERROR [2021-09-17 10:49:43.24]: Failed to upload release
INFO [2021-09-17 10:49:43.24]: Successfully generated documentation at path '/Users/distiller/project/ios/fastlane/README.md'

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | default_platform                | 0           |
| 2    | setup_circle_ci                 | 0           |
| 3    | Switch to ios certificates lane | 0           |
| 4    | match                           | 2           |
| 5    | gym                             | 1702        |
| 6    | Switch to ios appcenter lane    | 0           |
| 💥   | appcenter_upload                | 36     

bundler: failed to load command: fastlane (/Users/distiller/.gem/ruby/2.7.3/bin/fastlane)
Traceback (most recent call last):
	49: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `<main>'
	48: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `load'
	47: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
	46: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	45: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
	44: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
	43: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	42: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
	41: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	40: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	38: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:474:in `exec'
	37: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:28:in `run'
	36: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `kernel_load'
	35: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `load'
	34: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `<top (required)>'
	33: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `load'
	32: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
	31: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	30: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	29: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	28: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	27: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	26: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	25: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	24: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	23: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	22: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:64:in `block (2 levels) in parsing_binding'
	15: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	13: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	12: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:43:in `block (2 levels) in parsing_binding'
	10: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:356:in `run'
	 2: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:270:in `run_release_upload'
	 1: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Failed to upload release (FastlaneCore::Interface::FastlaneError)
	49: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `<main>'
	48: from /Users/distiller/.gem/ruby/2.7.3/bin/bundle:23:in `load'
	47: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
	46: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	45: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
	44: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
	43: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	42: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
	41: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	40: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	38: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli.rb:474:in `exec'
	37: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:28:in `run'
	36: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `kernel_load'
	35: from /Users/distiller/.gem/ruby/2.7.3/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `load'
	34: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `<top (required)>'
	33: from /Users/distiller/.gem/ruby/2.7.3/bin/fastlane:23:in `load'
	32: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
	31: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	30: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	29: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	28: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	27: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	26: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	25: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	24: from /Users/distiller/.gem/ruby/2.7.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	23: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	22: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:64:in `block (2 levels) in parsing_binding'
	15: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	13: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	12: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:43:in `block (2 levels) in parsing_binding'
	10: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:356:in `run'
	 2: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:270:in `run_release_upload'
	 1: from /Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/distiller/.gem/ruby/2.7.3/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Failed to upload release\e[0m (FastlaneCore::Interface::FastlaneError)

**My fastfile**
```
default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
      match(
        app_identifier: "com.MyAPP.app.test",
        type: "adhoc",
        shallow_clone: true,
        verbose: true,
        git_branch: "master",
        verbose: true,
        generate_apple_certs: true
      )
  end

  desc 'Upload build to appcenter'
  lane :appcenter do
    appcenter_upload(
            api_token: "sometoken",
            owner_name: "org-org",
            owner_type: "organization", # Default is user - set to organization for appcenter organizations
            app_name: "MyAPP-Test-1",
            file: "./MyAPPTest.ipa",
            destinations:"Mygroup"
          )
  end



  desc 'Beta build'
  lane :test do
    certificates
    gym(
        scheme: "MyAPPTest",
        workspace: './MyAPP.xcworkspace',
        configuration: "Release"
      )
    appcenter
  end

end
```

**Comment by clarissaj** [comment]
@saaaab1213 did you ever figure out why this was happening? I seem to have the same issue

**Comment by clarissaj** [comment]
never mind! I figured out the issue for us was that the schema configuration we were trying archive was somehow missing the app's marketing version in the build settings.. once I added that back in, all was golden!
