### ISSUE TITLE
Add support for ruby 3 -> wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by gmoraleda** [microsoft/fastlane-plugin-appcenter#283]
I'm integrating this plugin into my Fastfile. Although the `appcenter_upload` action works flawlessly, I'm getting an error with the action `appcenter_fetch_devices`:
> wrong number of arguments (given 2, expected 1)

Here the backtrace:
> ["/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/3.0.0/csv.rb:1559:in parse'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_fetch_devices_action.rb:65:in block (2 levels) in write_devices'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_fetch_devices_action.rb:64:in each'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_fetch_devices_action.rb:64:in block in write_devices'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/3.0.0/csv.rb:1438:in open'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_fetch_devices_action.rb:59:in write_devices'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-plugin-appcenter-1.11.1/lib/fastlane/plugin/appcenter/actions/appcenter_fetch_devices_action.rb:55:in run'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:263:in block (2 levels) in execute_action'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in execute_action'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:255:in block in execute_action'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in chdir'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in execute_action'", "/Users/gmoraleda/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:157:in `tri…

If I fallback to ruby 2.7.4, the actions works again (using the same arguments).

**Comment by oskargargas** [comment]
Also run into this problem. Thanks for the tip with downgrade to 2.7.4.
Please fix it or at least mention in Readme that 3.0 is not supported.
