### ISSUE TITLE
 certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by amazted** [microsoft/fastlane-plugin-appcenter#286]
After i run bundle exec fastlane appcenter_uat --verbose .  The error log just like below.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | appcenter_upload | 113         |
+------+------------------+-------------+

DEBUG [2021-11-30 00:01:18.03]: All plugins are up to date
ERROR [2021-11-30 00:01:18.03]: fastlane finished with errors
ERROR [2021-11-30 00:01:18.03]: -----------------------------------------------------------------------
ERROR [2021-11-30 00:01:18.04]: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
ERROR [2021-11-30 00:01:18.04]:
ERROR [2021-11-30 00:01:18.04]: SSL errors can be caused by various components on your local machine.
ERROR [2021-11-30 00:01:18.04]:
ERROR [2021-11-30 00:01:18.04]: The best solution is to use the self-contained fastlane version.
ERROR [2021-11-30 00:01:18.04]: Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries
ERROR [2021-11-30 00:01:18.04]:  - Use Homebrew
ERROR [2021-11-30 00:01:18.04]:     - update brew with `brew update`
ERROR [2021-11-30 00:01:18.04]:     - install fastlane using:
ERROR [2021-11-30 00:01:18.04]:       - `brew cask install fastlane`
ERROR [2021-11-30 00:01:18.04]:  - Use One-Click-Installer:
ERROR [2021-11-30 00:01:18.04]:     - download fastlane at https://download.fastlane.tools
ERROR [2021-11-30 00:01:18.04]:     - extract the archive and double click the `install`
ERROR [2021-11-30 00:01:18.04]: -----------------------------------------------------------
ERROR [2021-11-30 00:01:18.04]: for more details on ways to install fastlane please refer the documentation:
ERROR [2021-11-30 00:01:18.04]: -----------------------------------------------------------
ERROR [2021-11-30 00:01:18.04]:         🚀       https://docs.fastlane.tools          🚀
ERROR [2021-11-30 00:01:18.04]: -----------------------------------------------------------
ERROR [2021-11-30 00:01:18.04]:
ERROR [2021-11-30 00:01:18.04]: You can also install a new version of Ruby
ERROR [2021-11-30 00:01:18.04]:
ERROR [2021-11-30 00:01:18.04]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
ERROR [2021-11-30 00:01:18.04]: - If you use system Ruby:
ERROR [2021-11-30 00:01:18.04]:   - Run `brew update && brew install ruby`
ERROR [2021-11-30 00:01:18.04]: - If you use rbenv with ruby-build:
ERROR [2021-11-30 00:01:18.04]:   - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
ERROR [2021-11-30 00:01:18.04]:   - Run `rbenv global 2.3.1` to make it the new global default Ruby version
ERROR [2021-11-30 00:01:18.04]: - If you use rvm:
ERROR [2021-11-30 00:01:18.04]:   - First run `rvm osx-ssl-certs update all`
ERROR [2021-11-30 00:01:18.04]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
ERROR [2021-11-30 00:01:18.04]:
ERROR [2021-11-30 00:01:18.04]: If that doesn't fix your issue, please google for the following error message:
ERROR [2021-11-30 00:01:18.04]:   'SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)'
ERROR [2021-11-30 00:01:18.04]: -----------------------------------------------------------------------
DEBUG [2021-11-30 00:01:18.04]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/devops/.rbenv/versions/2.6.5/bin/fastlane)

**Comment by DmitriyKirakosyan** [comment]
Hi @amazted , this doesn't look like an issue in fastlane-plugin-appcenter, but rather related to your environment setup. Have you tried to perform the suggestions in the error output?

**Comment by DmitriyKirakosyan** [comment]
Closinga s stale.
