### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by andrewsuiter** [microsoft/fastlane-plugin-appcenter#288]
Uploading to fastlane using the plugin:
fastlane-plugin-appcenter | 1.11.1  | appcenter_fetch_version_number, appcenter_fetch_devices, appcenter_upload
I am getting a 504 Gateway Time-out

**Comment by andrewsuiter** [comment]
looks like there are issues with AppCenter: https://status.appcenter.ms/incidents/bcm67wq93x3t

**Comment by andrewsuiter** [comment]
issue is still happening

**Comment by tomachi** [comment]
This is also happening to us now.

**Comment by picninim** [comment]
Same here, logs return with HTML

[32mPlease update using `bundle update fastlane`[0m
/Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.196.0/spaceship/lib/spaceship/client.rb:763:in `parse_response': \e[31m[!]  (Spaceship::UnexpectedResponse)
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Gateway Timeout</h3>
    <p>Correlation Key: YTKJMAQ7FAGOUOCQBAHIBVDWLU</p>
</div>
</body>
</html>

**Comment by DmitriyKirakosyan** [comment]
Hi @andrewsuiter , @tomachi , @picninim , are you still experiencing this issue?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
