### ISSUE TITLE
appcenter_upload failed but still mark as passed on Jenkins

### ISSUE THREAD

**Issue by billypchan** [microsoft/fastlane-plugin-appcenter#289]
Hi all. I would like to ask how to handle Error 429 when running appcenter_upload on Jenkins. I got this error recently:
```
[13:01:26]: ------------------------------
[13:01:26]: --- Step: appcenter_upload ---
[13:01:26]: ------------------------------
[13:01:26]: Starting release upload...
[13:01:27]: Error 429: {"message"=>"The server is busy now. Try again later", "statusCode"=>429, "code"=>"Too Many Requests"}
[13:01:27]: Starting dSYM upload...
[13:01:27]: Uploading dSYM...
```

The uploaded app is not appear on app center but Jenkins still mark it as succeeded.

**Comment by clarissaj** [comment]
yep seeing same issue, docs don't seem to point out how we can know if the upload has failed. maybe this needs to be an enhancement?

**Comment by lholman** [comment]
https://status.appcenter.ms/ shows a reported issue around distribution - reported on Monday 😞 
```
Investigating - Due to high load to our servers, customers can experience "Too Many Request" response when creating a new release.
Dec 20, 15:58 UTC
```

**Comment by dragus0** [comment]
+1

**Comment by sittingbool** [comment]
I think for me its not even being executed. It says green, runtime 0 sek, nothing seemed to have happened but no error output

**Comment by MikhailSuendukov** [comment]
Hi @sittingbool at the moment, the AppCenter is experiencing problems with the Build service. Please try again after the problem is fixed. You can monitor the service status [here](https://status.appcenter.ms/).
If the problem is not fixed, please let us know.
