### ISSUE TITLE
appcenter_fetch_devices not working anymore due to destinations: *

### ISSUE THREAD

**Issue by pappalar** [microsoft/fastlane-plugin-appcenter#290]
```
appcenter_fetch_devices(
      api_token: ENV["APPCENTER_TOKEN"],
      owner_name: "XX",
      app_name: "XX",
      destinations: "*",
      devices_file: appcenter_file
    )
```

is not working anymore with `*` as it returns only Collaborators devices.

However this is not what the README Docs specifies:

```destinations: "*", # Default is 'Collaborators', use '*' for all distribution groups```

# Debugging the issue: 
API https://api.appcenter.ms/v0.1/apps/XX/XX/distribution_groups

Only returns 

```

  {
    "id": "00000000-0000-0000-0000-000000000000",
    "name": "Collaborators",
    "origin": "appcenter",
    "display_name": "Collaborators",
    "is_public": false
  }
]
```

instead of all distribution groups.

this seems to be the issue.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
