### ISSUE TITLE
Exception while uploading dSYM

### ISSUE THREAD

**Issue by arthurlerke** [microsoft/fastlane-plugin-appcenter#295]
If there is a dSYM found in the script the plugin throws this exception. Seems to be same as: #162 
The error:
```
no implicit conversion of Symbol into Integer (TypeError)
	from [..]/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-plugin-appcenter-2.0.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:81:in `run_dsym_upload'
```

Happens with any plugin version and ruby version I tried. I only found that if I comment out the line [`values[:dsym_path] = dsym_path`](https://github.com/microsoft/fastlane-plugin-appcenter/blob/293e4fcb439ef4463bf755f1753ab4eca5a660ac/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L81) in `appcenter_upload_action.rb` it all works fine and the upload succeeds.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
