### ISSUE TITLE
Feature Request: get a list of unprovisioned devices

### ISSUE THREAD

**Issue by joeybaker** [Microsoft/fastlane-plugin-appcenter#3]
Getting a list of the unprovisioned devices for an app would be very useful. We could then pass that list to https://docs.fastlane.tools/actions/#register_devices to automate adding new users.

**Comment by evkhramkov** [comment]
It is in future plans but no ETA. Stay in touch with our [roadmap](https://docs.microsoft.com/en-us/mobile-center/general/roadmap)

**Comment by bytenik** [comment]
@evkhramkov Are there plans for this now 1.5 years later? As HockeyApp is sunsetting at the end of this year, we are hoping this will be resolved before then.
