### ISSUE TITLE
fastlane action appcenter_upload not found

### ISSUE THREAD

**Issue by thenetexperts** [Microsoft/fastlane-plugin-appcenter#30]
After installing the plugin in fastlane, the actions list contains `mobile_center_upload` but not `appcenter_upload`. I can see there was a renaming taking place in the past, so i am not sure if this did not propagate to the latest release, or something is wrong with my fastlane environment.

**Comment by evkhramkov** [comment]
Hi @thenetexperts, sorry for delay. If you used `mobile_center_upload` before, you need to remove it and install by:
```
fastlane add_plugin appcenter
```

**Comment by thenetexperts** [comment]
Hey, thanks for the info! That makes total sense, noted 👍
