### ISSUE TITLE
Code Push Error - The "release-react" command must be executed in a React Native project folder.

### ISSUE THREAD

**Issue by uyend** [microsoft/fastlane-plugin-appcenter#305]
Hi I'm getting this error. Is there a way to specify execution path directory? 

```
failed with exception "Unable to find or read "package.json" in the CWD. 
The "release-react" command must be executed in a React Native project folder."
```

**Comment by AnatolyPristensky** [comment]
Hello @uyend, you should check:

if the file `package.json` exists
and if it has the `"name": "..."` parameter

**Comment by AnatolyPristensky** [comment]
Closing, please feel free to reopen it in case of new information.
