### ISSUE TITLE
How to deploy to multiple distribution types

### ISSUE THREAD

**Issue by matt-dalton** [microsoft/fastlane-plugin-appcenter#308]
Here is my Fastfile Android upload section:
```
  lane :deploy_to_appcenter do |options|
    if ENV['ENV'] == 'production'
      destinations = 'Alpha'
      destination_type = 'store'
    else
      destinations = 'Collaborators'
      destination_type = 'group'
    end
    appcenter_upload(
      api_token: ENV['ANDROID_APPCENTER_API_TOKEN'],
      owner_name: ENV['APPCENTER_USERNAME'],
      app_name: ENV['ANDROID_APPCENTER_APP_ID'],
      file: ENV['ANDROID_APK_PATH'],
      release_notes: %x[#{release_notes_command}],
      destinations: destinations,
      destination_type: destination_type
    )
  end
```

**My Problem**
For production builds, I obviously want to deploy to my test track (see above). However, it's also useful to use Appcenter's download page to allow people to easily test specific versions (`https://install.appcenter.ms/users/[org_name]/apps/[app_name]`).

But it seems as though builds don't show on that download page unless you release to collaborators(?). In which case, I also need to distribute my production builds to Collaborators.

Is there a way to distribute to both stores and collaborators? Or is there a different way of achieving what I want?

**Comment by DmitriyKirakosyan** [comment]
There is no option to distribute to `store` and `group` at the same time. You can run the task two times, for each destination type.

**Comment by matt-dalton** [comment]
Am I right in thinking a build has to be distributed to Collaborators to appear on the download list?

**Comment by DmitriyKirakosyan** [comment]
There are two types of groups: public and private. The link will be accessible for everyone if you deploy to a public group.

**Comment by DmitriyKirakosyan** [comment]
If you deploy to a private group, the build will be visible for app testers only.

Closing this issue but feel free to ask any additional questions.

**Comment by matt-dalton** [comment]
Yeah...so sounds like it would still be necessary to deploy to a store AND a group.

Your [workaround](https://github.com/microsoft/fastlane-plugin-appcenter/issues/308#issuecomment-1263278997) works, it would be nice to do it in one though since these seems like an extremely common use-case and it unnecessarily makes our pipeline times longer
