### ISSUE TITLE
Add missing Plist file (and other) params to codepush action

### ISSUE THREAD

**Issue by j-evs** [microsoft/fastlane-plugin-appcenter#309]
Is it possible to add a [Plist file param](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/cli#plist-file-parameter-ios-only) for `appcenter_codepush_release_react` action? Or better yet [all possible CLI params](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/cli#releasing-updates-react-native) to enable full appcenter CLI support via the appcenter fastlane plugin?

Thanks!

**Comment by DmitriyKirakosyan** [comment]
Hi @j-evs , the idea of plugin is to simplify the interface. If you need advanced setup you can use appcenter-cli instead.

**Comment by AnatolyPristensky** [comment]
@j-evs, we don't hear from you for a while, so I'm closing this issue. 
Please, feel free to reopen it in case of new information.
