### ISSUE TITLE
Upload to appcenter failing

### ISSUE THREAD

**Issue by harasai** [microsoft/fastlane-plugin-appcenter#310]
Hi I am seeing errors while uploading app to appcenter.

Environment:
OS: MacOS
plugins: 
gem 'fastlane', '2.210.1'
gem 'fastlane-plugin-appcenter', '2.0.0'

Error1:
Faraday http exception getting app: execution expired
App with name Explorer-Enterprise not found, create one?

Error2:
Waiting for release to be ready...
Faraday http exception polling for release id: execution expired

**Comment by AnatolyPristensky** [comment]
Hello @harasai, this is related to the current outage on our side. The team is working to mitigate it.
