### ISSUE TITLE
[Bug] Failed to open TCP connection to api.appcenter.ms:443

### ISSUE THREAD

**Issue by hffmnn** [microsoft/fastlane-plugin-appcenter#316]
Starting today I get this error when trying to upload an ipa:

```
Faraday http exception getting app: Failed to open TCP connection to api.appcenter.ms:443
App with name some_name not found, create one? (y/n)
n
```

Running a

```
appcenter apps list --token <used token>
```

prints out the app name.

Because I did a ruby and fastlane update the other day, I am not 100% sure if this is on my site or if it is a problem with his plugin. Is there some way to debug the problem?

Note: I didn't touch the config at all. This setup was running for years this way.

**Comment by aleksandr-dorofeev** [comment]
Hello @hffmnn , recently there was an outage on our side and the team successfully eliminated them. 
Is the problem still relevant?

**Comment by AnatolyPristensky** [comment]
Closing this issue since appcenter status page is green. Feel free to reopen it in case of new repro.

**Comment by hffmnn** [comment]
Hi @aleksandr-dorofeev and thanks for the info. From my side, it works again. 

@AnatolyPristensky Sadly the status page never showed any sign that something isn't working on the backend (last issue is from 19.04. this issues is from the 20th), so saying

> Closing this issue since appcenter status page is green. Feel free to reopen it in case of new repro.

isn't constructive at all.

Still the issue can be closed.
