### ISSUE TITLE
Unhelpful error when `owner_name` is incorrectly formatted

### ISSUE THREAD

**Issue by mylogon341** [microsoft/fastlane-plugin-appcenter#320]
When I have
```ruby
 appcenter_upload(
      api_token: "blah",
      owner_name: "company name",
      owner_type: "organization",
      app_name: "my-app-name",
      file: "file.ipa",
      dsym: "whatever",
      destinations: "develop",
      notify_testers: false
    )
```
I accidentally put a space in the owner name however the error that I get is 
`Provided app_name: 'my-app-name' is not in a valid format. Please ensure no special characters or spaces in the app_name.`

This lead to a good few minutes of head scratching until I finally realised I'd actually made a mistake in the owner_name.

Can we have a slightly smarter validator that gives an error for the right thing, please? :)
Thanks

**Comment by MikhailSuendukov** [comment]
Hello @mylogon341, thanks for reaching out to us. Are you currently experiencing difficulties, or did you manage to fix your problem?

**Comment by mylogon341** [comment]
I managed to resolve this my just putting the `-` in the name for the owner, which was the real error.

**Comment by MikhailSuendukov** [comment]
Thank you very much for your message, we are glad that your problem has been solved. I am closing this issue, but if you have any more questions, feel free to reopen it.

**Comment by mylogon341** [comment]
Well I wouldn't say it was completed. My original post pointed out I fixed the issue, but the sentiment of the gh issue is that the wording of the error is unhelpful and could do with improvement.
It appears that the catch-all is to complain about the app name, which isn't appropriate here as it was the owner name that was at fault.

**Comment by MikhailSuendukov** [comment]
Yes, you are right, this can be fixed and quite easily, if you want, you are welcome to contribute. This is the good first issue for that.
