### ISSUE TITLE
appcenter_upload no longer uploading both .aab and .apk, only .aab

### ISSUE THREAD

**Issue by shawna-donnelly** [microsoft/fastlane-plugin-appcenter#329]
Starting on 10/23, we started seeing only the .aab being uploaded to app center, even though the code didn't change. I re-ran a previously working github action (uploaded both apk and aab previously), and again it only uploaded the .aab. 

We are using version 2.1.1. 

Nothing with this call has changed: 

```lane :to_appcenter do
    appcenter_upload(
      api_token: ANDROID_APPCENTER_KEY,
      owner_name: 'OurOrganization',
      owner_type: 'organization',
      app_name: ANDROID_APPCENTER_APP_NAME,
    )

**Comment by AnatolyPristensky** [comment]
Hello @shawna-donnelly, I've contacted appropriate team on this issue. 
It would be great if you will provide more information like logs for example.

**Comment by AnatolyPristensky** [comment]
@shawna-donnelly, we haven't heard from you for a while, so I'm closing this issue. 
Please, feel free to reopen it if you have more information.
