### ISSUE TITLE
Uploading index.ios.map

### ISSUE THREAD

**Issue by Jeanmsilva89** [microsoft/fastlane-plugin-appcenter#33]
I'm not seeing the index.ios.map file being uploaded to the Symbols when using this plugin. According to these instructions, it should include a source maps file. 

https://docs.microsoft.com/en-us/appcenter/crashes/react-native

> Create a ZIP file with the dSYM package on your Mac and the JavaScript source map of your app. The source map should named "index.ios.map"

When I download my Uploaded Symbol, the index.ios.map is not there. Does anyone know how to make make sure the source map files are uploaded?

Thanks

**Comment by FahadRS** [comment]
@Jeanmsilva89  did you find any way to fix this

**Comment by FahadRS** [comment]
Ok I found work around that is working for me, before uploading the dSYM zip the index.ios.map file and dSYM through the following command 

`zip testingapp.app.dSYM.zip index.ios.map testingapp.app.dSYM`

then use the upload center upload task and pass it the path of zip file 

appcenter_upload(
    api_token: "token",
    owner_name: "owner",
    app_name: "TestingApp",
    upload_dsym_only: true,
    dsym: "./build/Build/Products/Release-iphonesimulator/testingapp.app.dSYM.zip"
)

it is working perfectly for me

**Comment by DmitriyKirakosyan** [comment]
Hi @Jeanmsilva89 , considering the @FahadRS's workaround, is this feature request still relevant for you?

**Comment by simon-assistiq** [comment]
Whenever I try to do this (zipping the dSYM.zip with the .map file), whether through the plugin or manually, regardless of what filenames I use, the result is always "No symbols found"

**Comment by DmitriyKirakosyan** [comment]
@simon-assistiq, thanks for providing information that could benefit others. It's great to hear that it's working for you now. I'm closing this issue, but if anyone continues to encounter the problem, please don't hesitate to reach out.
