### ISSUE TITLE
The "release-react" command must be executed in a React Native project folder."

### ISSUE THREAD

**Issue by QuangBinhDinh** [microsoft/fastlane-plugin-appcenter#334]
I have a React Native project which has an Android folder and an iOS folder, both configured Fastlane. However when I run `appcenter codepush release-react` it throw me the error above. I know that the command `release-react` must be run at the project root, but I don't know how to make a lane inside `Fastfile` run at the root (the parent folder). Any help would be appreciated

**Comment by DmitriyKirakosyan** [comment]
Closing. Please reopen if you are still interested.
