### ISSUE TITLE
How to fetch only the latest version and the latest build number available

### ISSUE THREAD

**Issue by EArminjon** [microsoft/fastlane-plugin-appcenter#335]
I would like to fetch the highest version available on app center which can also not be the latest one uploaded.
How to do that ? 

Example :

I upload version 2.0.0+10 and after that a little patch for my 1.9.0+9 app named 1.9.1+11.

The appcenter_fetch_version_number function will return the data for 1.9.1+11.

The goal for me is to find a solution to automatically create the new 2.0.0+12 version. Which require a function to get the highest version available on appcenter and a function to get the latest build number. 

For the latest build number i can use appcenter_fetch_version_number.
For the latest version number i didn't see any solution.

**Comment by DmitriyKirakosyan** [comment]
Hi @EArminjon , thank you for reaching out!

`appcenter_fetch_version_number` returns the last uploaded release. If you want to get the newest release by version, you can use appcenter-cli's command `appcenter distribute releases list` and parse the output.
