### ISSUE TITLE
Upload .zip in custom app via Fastlane

### ISSUE THREAD

**Issue by alejandroruizponce** [microsoft/fastlane-plugin-appcenter#343]
```
    appcenter_upload(
      api_token: <api token>,
      app_name:  <api name>,
      app_os: 'Custom',
      app_platform: 'Custom',
      owner_name: <owner name>, 
      file: File.join(FILE_PATH, "#{fileName}.app.zip")
    )
```

I have a `.app.zip` file that I try to upload from Fastlane to a custom app created but I get the following error in console:
`Error fetching release: A problem occured while extracting your app. (Correlation ID: 6680e614-8003-4e14-8a2e-0b942169ee61)`

To provide more context, it is an iOS app that I need to upload as custom because it is not an `.ipa` what I generate but a simulator app with `.app` extension. I have seen that appcenter.com allows me to upload it without problems but from Fastlane I can't get it.

**Comment by DmitriyKirakosyan** [comment]
Hi @alejandroruizponce , thank you for reaching out! Unfortunately, distributing apps for a simulator is not supported.
