### ISSUE TITLE
Appcenter codepush support

### ISSUE THREAD

**Issue by Amurmurmur** [Microsoft/fastlane-plugin-appcenter#37]
Since those plugins that were mentioned in another issue https://github.com/Microsoft/fastlane-plugin-appcenter/issues/26#issuecomment-352687919
dont support appcenter code-push, I was wondering if this plugin will support appcenter codepush ?
Seems to be quite reasonable since this is an official fastlane plugin to support appcenter, makes sense to include codepush feature.

**Comment by derpixeldan** [comment]
Sorry, but we don't have plans to support codepush.

**Comment by CAMOBAP795** [comment]
@derpixeldan any reason behind this decision?

**Comment by derpixeldan** [comment]
We're focusing on the HockeyApp shutdown and have to prioritize work accordingly.

**Comment by CAMOBAP795** [comment]
@derpixeldan, thanks for answer, BTW will you accept contribution in this direction?

**Comment by derpixeldan** [comment]
@CAMOBAP795 yes, contributions are most appreciated, that's one of the reasons it's open source.

**Comment by Pranit-Harekar** [comment]
Please use this dedicated CodePush plugin: https://github.com/Pranit-Harekar/fastlane-plugin-codepush
