### ISSUE TITLE
Cannot set if version requires update from testing.

### ISSUE THREAD

**Issue by hdominguezglobant** [Microsoft/fastlane-plugin-appcenter#39]
Guessing this should be added as command from fastlane.

<img width="313" alt="screen shot 2018-10-26 at 4 14 44 pm" src="https://user-images.githubusercontent.com/30051535/47592780-48f2c380-d93a-11e8-8201-db3734c0aa4b.png">

**Comment by derpixeldan** [comment]
The option to set releases mandatory was introduced with [version 0.2.0](https://github.com/Microsoft/fastlane-plugin-appcenter/releases/tag/v0.2.0).
