### ISSUE TITLE
Option to upload a mac app

### ISSUE THREAD

**Issue by talshr** [microsoft/fastlane-plugin-appcenter#44]
Hi,

It seems it's impossible to use this plugin (yet) to upload mac apps.
(e.g. zip file with the .app).
I know it's possible to use the website to upload and distribute the app, but seemingly not through the plugin.

**Comment by sseyod** [comment]
I would also like this implemented please!

**Comment by jpeg-ms** [comment]
The PR #36 was merged, resolving this request.
