### ISSUE TITLE
Step failure is incorrectly marked as a success

### ISSUE THREAD

**Issue by Dids** [Microsoft/fastlane-plugin-appcenter#5]
This is technically two separate issues:
- Server error for unknown reasons (no explanation anywhere as to why)
- Validation doesn't catch the error, marking the step as a success

```bash
[04:36:14]: ----------------------------------
[04:36:14]: --- Step: mobile_center_upload ---
[04:36:14]: ----------------------------------
[04:36:14]: Starting release upload...
[04:36:15]: Uploading release binary...
[04:36:27]: Binary uploaded
[04:36:28]: Release committed
[04:36:29]: Error adding to group 500: {"code"=>"internal_server_error", "message"=>"<UID>: internal error"}
[04:36:29]: Starting dSYM upload...
[04:36:29]: Uploading dSYM...
[04:36:31]: dSYM uploaded
```

**Comment by Dids** [comment]
The actual errors seems to come from specifying `release_notes`.

I've previously used this to add a changelog, but for some reason it doesn't seem to work anymore:
```ruby
mobile_center_upload(
  ...
  release_notes: sh("cat ../CHANGELOG.md 2>/dev/null")
)
```

**Comment by evkhramkov** [comment]
@Dids could you please run fastlane with `DEBUG=true fastlane ...` for showing all output.

Your example works fine for me:

<img width="860" alt="2017-11-16 11 02 05" src="https://user-images.githubusercontent.com/27571887/32880148-a3832ae2-cabd-11e7-9bd9-794b6c97d26a.png">

With `DEBUG=true` you should see something like this

<img width="522" alt="2017-11-16 11 03 34" src="https://user-images.githubusercontent.com/27571887/32880198-d7a2be28-cabd-11e7-8e73-44d227b593ca.png">

**Comment by Dids** [comment]
@evkhramkov Thanks, will do!

I should also note that I'm generating the changelog with [github-changelog-generator](https://github.com/skywinder/github-changelog-generator), which seems to do a lot of escaping in the markdown it produces.

However, from all the markdown editors/previewers I've tested, it's still valid markdown, but the App Center parser might be having issues with them, although I'm only guessing at this point.

Here's a sample of the generated markdown (output is from my CI, so don't mind the timestamps etc.): https://pastebin.com/zYsngvLz

**Comment by evkhramkov** [comment]
@Dids thanks for example, seems your guess is right, I reproduced the same error. Will investigate this.

**Comment by evkhramkov** [comment]
@Dids this is because notes are too long, App Center has a limit with 5000 characters for release notes:

<img width="585" alt="2017-11-16 13 11 21" src="https://user-images.githubusercontent.com/27571887/32885811-ae0401d2-cacf-11e7-9b11-30dd62d17e14.png">

So we'll add a check for that in fastlane plugin, thanks for the feedback!

**Comment by Dids** [comment]
Just FYI, this seems to work as a workaround for right now:

```ruby
# Read the changelog to an environment variable
ENV["CHANGELOG"] = sh('echo "$(IFS= cat ../CHANGELOG.md 2>/dev/null)"')

# Truncate the changelog to 5000 characters
ENV["CHANGELOG"] = sh('echo "${CHANGELOG:0:4999}"')
```

Ideally it'd truncate enough space to leave a markdown link, saying something like "read more".

**Comment by evkhramkov** [comment]
> Would it be possible to automatically clip the release notes if they go over 5000 characters?
Yes, sure it is possible

**Comment by evkhramkov** [comment]
@Dids please update `fastlane-plugin-appcenter` to `v0.1.5`, release notes clipping added in #7

**Comment by Dids** [comment]
@evkhramkov Is there a non-interactive way of clipping? Running this in a CI will just hang, since there's nobody there to confirm it in a headless environment.

**Comment by evkhramkov** [comment]
@Dids nice suggestion, thanks. Please update to `v0.1.6`, now it will clip release notes automatically by default, and you can provide release notes link by `release_notes_link` option.
To disable auto-clipping use `should_clip: false` option
