### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by kemalenver** [Microsoft/fastlane-plugin-appcenter#52]
I'm getting the following error when trying to upload an app, when the app_name isn't already created.  This use case works fine in Hockey, but seems to be a problem with App Center.  We generate new build names for each of our feature branches which is why we need this.

In the log I see that it tries to prompt to create the app name.  Can we have an option that automatically creates the app without user input based on what we entered as the app_name?

```
appcenter_upload(
      api_token: ENV["APP_CENTER_API_KEY"],
      owner_name: ENV["APP_CENTER_OWNER_NAME"],
      app_name: build_name,
      ipa: "./App.ipa"
    )
```

**Comment by ElieSauveterre** [comment]
While waiting for a fix, I managed to create an app with curl. It's working for organizations.
In your Fastfile add
`
sh './appcenter-create-app.sh ENV["APPCENTER_OWNER_NAME"] ENV["APPCENTER_API_TOKEN"] ENV["APPCENTER_APP_NAME"]'
`

Create a file appcenter-create-app.sh
`
#!/usr/bin/env bash

curl -v -X POST \
    "https://api.appcenter.ms/v0.1/orgs/$1/apps" \
    -H "accept: application/json" \
    -H "Content-Type: application/json" \
    -H "X-API-Token: $2" \
    -d "{ \"description\": \"$3\", \"display_name\": \"$3\", \"name\": \"$3\", \"os\": \"Android\", \"platform\": \"Cordova\"}"
`

**Comment by kemalenver** [comment]
Cheers for that Ellie, I'll take a look 👍

**Comment by derpixeldan** [comment]
To unify the conversation handling in referenced ticket.

**Comment by vanlooverenkoen** [comment]
This should be an option to automatically create a new app.
