### ISSUE TITLE
Android Mapping.txt

### ISSUE THREAD

**Issue by m-ruhl** [microsoft/fastlane-plugin-appcenter#54]
Hello,

in the HockeyApp action we used the "dysm" property to upload the mapping.txt.
This does not work with the AppCenter-Plugin.. See the screenshot.
![mapping_files](https://user-images.githubusercontent.com/867772/53346434-52eff780-3917-11e9-9953-e599da6eee4b.png)

What is the right way, to upload it?

Thanks
Michael

**Comment by enizbilgin** [comment]
Hi,

The request body inside of AppCenterHelper needs to be edited as below. Thus it will have a parametric structure.

<img width="622" alt="Screen Shot 2019-04-26 at 15 16 35" src="https://user-images.githubusercontent.com/11583009/56808690-bd9bb180-683a-11e9-9d65-0d7be1982178.png">
