### ISSUE TITLE
Feature Request: disable email notifications

### ISSUE THREAD

**Issue by herbeth1u** [Microsoft/fastlane-plugin-appcenter#55]
Hello.

In the HockeyApp Fastlane action, we had access to a "notify" parameter, with which it was possible to disable automatic email notifications when uploading a new release. See https://docs.fastlane.tools/actions/hockey/

This parameter seems to be missing from the new appcenter_upload action, and emails are being sent to everyone for each release. I can't seem to find a way to have any control over this.

Could it be possible to add this parameter for appcenter_upload as well?
Thanks.

**Comment by derpixeldan** [comment]
We'll be adding that soon.

**Comment by c0un7-z3r0** [comment]
I opened a while back #38 to add this feature.

**Comment by evkhramkov** [comment]
@c0un7-z3r0 thanks for your contribution, but we'll be switching to new distribution api in upcoming update, and silent release option will be part of this changes
