### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by chojnac** [Microsoft/fastlane-plugin-appcenter#56]
Is this project still alive? The last merge is from a year ago and there are pending PR that no one is merging. 
Judging by the state of this plugin maintaining, choosing Appcenter.ms was not a good idea :(

**Comment by derpixeldan** [comment]
@chojnac apologize for the silence that's ruling here. This is not an excuse, but we've been very focused on the transition from HockeyApp to App Center and somewhat lost sight of the plugin. I'm currently developing the future strategy of the plugin, please bear with us. I'm updating the outcome here soon.

**Comment by derpixeldan** [comment]
@chojnac a few minor tweaks are coming to the plugin in the next days. Also we'll support `mandatory` and `notify_testers`.

**Comment by chojnac** [comment]
It's great to hear that, thank you for the quick answer and update.
