### ISSUE TITLE
Add optional parameters app OS, platform & display name

### ISSUE THREAD

**Issue by derpixeldan** [microsoft/fastlane-plugin-appcenter#58]
According to user feedback the app slug alone isn't helpful to identify the app and obviously any prompt breaks CI.

Proposal:
* Add optional parameters `app_os`, `app_platform`, `app_display_name` which will be used if the app slug not found
* If all parameters provided, there will be no prompts, so it will be possible to use the action in CI

References:
https://github.com/Microsoft/fastlane-plugin-appcenter/issues/17 https://github.com/Microsoft/fastlane-plugin-appcenter/issues/19 https://github.com/Microsoft/fastlane-plugin-appcenter/issues/52

**Comment by kemalenver** [comment]
@derpixeldan Great to see this is marked as an enhancement and assigned.  Just wondering if you can provide an ETA?  Once this is in I can migrate our CI from Hockey.  Thanks!

**Comment by evkhramkov** [comment]
Sorry for long delay. We published version `1.0.1` with this parameters
