### ISSUE TITLE
invalid distribution group name

### ISSUE THREAD

**Issue by emilioicai** [microsoft/fastlane-plugin-appcenter#64]
I recently updated to 0.2.1 . Everything seemed to be working fine until I tried distributing my app to the Testflight and Beta testers in Google play. Now I only get this error over and over:

```
Not found, invalid distribution group name
Group 'Alpha' was not found
```

This is th relevant code in my Fastfile:

```
# upload to appcenter
appcenter_upload(
      api_token: "<TOKEN>",
      owner_name: "<OWNER>",
      app_name: "<APPNAME>",
      notify_testers: true,
      group: "Alpha",
      release_notes: "<NOTES>",
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
)
```

Which makes me think something changed in the way appcenter retrieves the group id. Can you confirm this is the case? If so, how should I modify my Fastfile to reflect this change?

**Comment by emilioicai** [comment]
I can confirm the distribution group 'Alpha' exists in my App's appcenter setup

**Comment by evkhramkov** [comment]
Hello, sorry for that issue. At the moment, plugin supports distributing only to App Center distribution groups, you can’t target external destination (like TestFlight, or Google Play)

**Comment by emilioicai** [comment]
This was working before, any plans on supporting this feature in the future?

**Comment by evkhramkov** [comment]
Yes we will fix that soon, I hope we'll be able to release an update next week.
But due to API changes, which were adopted in `0.2.0` release, we'll have to introduce separate parameter to specify external stores.

Sorry again for that issue, but you still can try downgrading to `0.1.7`

**Comment by DennisPan** [comment]
My thoughts on this is to first refactor what we have and change `group` to `destinations`, and add `destination_type`, which is consistent with how App Center CLI does this (https://github.com/Microsoft/appcenter-cli/blob/master/src/commands/distribute/releases/add-destination.ts#L67) and App Center public APIs. Does this sound reasonable @evkhramkov ?

**Comment by evkhramkov** [comment]
@emilioicai we just released version `1.0.0` with stores support. You can use that like that:
```ruby
# upload to appcenter
appcenter_upload(
      api_token: "<TOKEN>",
      owner_name: "<OWNER>",
      app_name: "<APPNAME>",
      notify_testers: true,
      destinations: "Alpha",
      destination_type: "store",
      release_notes: "<NOTES>",
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
)
```

**Comment by emilioicai** [comment]
great!, thanks @evkhramkov

**Comment by jwilber99** [comment]
Hello all, I have been trying to use appcenter_upload() in my fastfile to upload our builds to the appcenter and the play / app store. It successfully uploads to the appcenter but it doesn't successfully upload to the stores. It tells me 'Not found, invalid distribution store name, store 'App Store' was not found'. 
The arguments I am using look like this:
appcenter_upload(
    file: options[:BUILD_OUTPUT],
    destinations: "App store",
    destination_type: "store",
    upload_build_only: true)

It doesn't recognize 'App store' as a name for a store. I have looked through the documentation and this one (link below) shows the 'destinations' as Alpha. I did try alpha but it tells me 'Not found, invalid distribution store name, store 'Alpha' was not found'. Example can be found above and at the link below
(Link: https://github.com/microsoft/fastlane-plugin-appcenter/blob/f46cb07ae3fad3cadd57e349c662f80cd769121f/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L709-L716)
In the 'fastlane-lugin-appcenter's readme, it says that 'Comma separated list of destination names, use '*' for all distribution groups if destination type is 'group'. Both distribution groups and stores are supported. All names are required to be of the same destination type (default: Collaborators)'

What I am trying to accomplish: upload our builds to the app center (already done, have multiple builds in there) AND have it be uploaded to both the Google Play Console and the App Store Connect.

The main question I have is: What are the values that can be used for 'destinations' when we are trying to upload to a store and not a group of testers within AppCenter? Can anyone help me with this I would REALLY appreciate it, thank you so much in advance! 

<img width="830" alt="Looper Store name not found build output" src="https://user-images.githubusercontent.com/124825025/217642477-6899f523-e723-49d8-a068-50ddb727383a.png">

**Comment by MikhailSuendukov** [comment]
Hi @jwilber99 which fastlane plugin version do you use?

**Comment by jwilber99** [comment]
Hello @MikhailSuendukov thank you so much for responding. I am using version 2.0.0 for 'fastlane-plugin-appcenter'. Should I be using a different version?

<img width="680" alt="Screenshot 2023-02-09 at 9 26 56 AM" src="https://user-images.githubusercontent.com/124825025/217857132-edec1575-cbbd-4897-8d58-8007c12a6584.png">
