### ISSUE TITLE
Shared values defined in non-default module

### ISSUE THREAD

**Issue by oklimberg** [Microsoft/fastlane-plugin-appcenter#66]
The default usage of lane_context, according to the [documentation](https://docs.fastlane.tools/actions/lane_context/), is `lane_context[SharedValues::BUILD_NUMBER]`.
Applying the format to this plugin `lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]` results in the following error: 
```NameError: [!] uninitialized constant Fastlane::Actions::SharedValues::APPCENTER_DOWNLOAD_LINK```

Instead, the user is required to type `lane_context[Fastlane::Helper::SharedValues::APPCENTER_DOWNLOAD_LINK]` which is not mentioned in the docs and only becomes clear when looking into the source code.

The SharedValues module should be moved to Fastlane::Actions where all other shared values are defined.

**Comment by evkhramkov** [comment]
Thank you for the fix!
Released this change in `0.2.2`
