### ISSUE TITLE
Option `group` is deprecated. Use `destinations` and `destination_type`

### ISSUE THREAD

**Issue by mengdd** [microsoft/fastlane-plugin-appcenter#79]
Previously used version is 0.22.

If "APPCENTER_DISTRIBUTE_GROUP" is defined as an environment variable.
Before it can be omitted, and all works well.

But now got the error message: 
```
Option `group` is deprecated. Use `destinations` and `destination_type`
```

So the two lines were added below the apk line:
```
       appcenter_upload(
           apk: "xxx/yyy/zzz.apk",
           destinations: ENV["APPCENTER_DISTRIBUTE_GROUP"],
           destination_type: "group"
        )
```
Still same error:
```
Option `group` is deprecated. Use `destinations` and `destination_type`
```

Finally found a fix: rename the environment variable to something else other than `APPCENTER_DISTRIBUTE_GROUP`, problem solved.

I think the readme needs to be updated to show the right way.

**Comment by DennisPan** [comment]
Thanks for pointing that out! #81 hopefully addresses this.

**Comment by DennisPan** [comment]
@mengdd Merged the changes. README should be updated. Thanks again for reporting!
