### ISSUE TITLE
No symbols founds in zip after appcenter_upload 

### ISSUE THREAD

**Issue by abramov7** [Microsoft/fastlane-plugin-appcenter#8]
I run the following command 

```
 appcenter_upload(
            api_token: "...",
            owner_name: "...",
            app_name: "...",
            upload_dsym_only: true,
            dsym: "dSYM path",
        )
```

A zip file is correctly uploaded on app center and I see it in the list of uploaded file but it says "No symbols found" with a size of 0B. I tried to download the zip file and the file correctly contains the symboles apart the fact that the dSym file is present a two places (at root and in a path that sounds like the complete path of the original location of the symbole file (e.g. ../bin/.../...dSym)

When repackaging the zip file with only the dSym file at root and then uploading again in appcenter, the symbols are found and everything works well.

**Comment by MrHubble** [comment]
How did you create the dsym zip file? Is it possible to use other commands found in [appcenter_upload_action.rb](https://github.com/Microsoft/fastlane-plugin-appcenter/blob/9f99aab3ee7d9bf971a2f72b59e3e2d5043fce77/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb)?

![screen shot 2017-11-28 at 5 33 00 pm](https://user-images.githubusercontent.com/2251631/33305488-608fc458-d462-11e7-9c3f-eca05403ab30.png)

**Comment by evkhramkov** [comment]
> Is it possible to use other commands found in appcenter_upload_action.rb?

@MrHubble this plugin provides single `appcenter_upload` fasltane action, `create_dsym_upload` is an internal method for calling App Center API.

Provided command `appcenter_upload(..., upload_dsym_only: true, dsym: "dSYM path")` is fine, it just takes file from the path and uploads it to App Center (and `create_dsym_upload` is used inside).

**Comment by abramov7** [comment]
@evkhramkov `appcenter_upload` works but uploaded zip package has a weird structure

>  dSym file is present a two places (at root and in a path that sounds like the complete path of the original location of the symbole file (e.g. ../bin/.../...dSym)

and this gives the mentioned bug

> No symbols founds in zip

**Comment by abramov7** [comment]
In fact the zip sent to app center is correct. It's on app center, that there seems to have an issue

<img width="1720" alt="screen shot 2017-11-28 at 18 07 03" src="https://user-images.githubusercontent.com/465495/33333414-11f96f88-d467-11e7-9a65-60993fbf6a1c.png">

Workaround is to download the zip (even if it says that it's 0B), delete the bin folder in the zip and then upload the zip again.

**Comment by abramov7** [comment]
@janpio dsym file is generated by a Xamarin.iOS build (using souyuz fastlane plugin)

**Comment by janpio** [comment]
Oh ok. Problem is here somewhere then probably: https://github.com/voydz/souyuz/blob/9f79826968ec97188f7e22ab9927fba9ce366273/lib/souyuz/generators/zip_dsym_command_generator.rb#L4

**Comment by MrHubble** [comment]
@Eversole 

>Provided command appcenter_upload(..., upload_dsym_only: true, dsym: "dSYM path") is fine, it just takes file from the path and uploads it to App Center (and create_dsym_upload is used inside).

Thanks for that. Doesn't App Center also require the source map of the app? Does this get created with `create_dsym_upload`?

Reference:

>Create a ZIP file with the dSYM package on your Mac and the JavaScript source map of your app. The source map should named "index.ios.map".

https://docs.microsoft.com/en-us/appcenter/crashes/react-native

**Comment by abramov7** [comment]
@janpio the generated dSym and zip files looks fine. It's the zip file present on AppCenter that has this strange structure.

**Comment by janpio** [comment]
Wait, so before you upload the file it is all correct, and only after uploading you get this strange structure? Wouldn't that be kind of impossible, as Appcenter can't know about the path of your local file if the uploaded zip doesn't contain that information? (Or am I misunderstanding something?)

**Comment by abramov7** [comment]
You are right, seems not possible but it's what I discovered this morning. I will re-test.

**Comment by abramov7** [comment]
I checked and the bug is as you said on soyouz side. @janpio Thanks for your help!

**Comment by janpio** [comment]
Thanks for reporting back. Hope you can get it fixed on their side.
