### ISSUE TITLE
Where is release_notes_link used?

### ISSUE THREAD

**Issue by tonyxiao** [microsoft/fastlane-plugin-appcenter#82]
I see that it's implemented here

https://github.com/microsoft/fastlane-plugin-appcenter/blob/master/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L77

However, when I go to our app center UI as well as the app center docs, I can't seem to find anything related to release notes link. Where is `release_notes_link` used inside app center once build has been uploaded?

**Comment by evkhramkov** [comment]
Hello @tonyxiao 

`release_notes_link` is optional parameter, and it used together with `should_clip` parameter in this case:
- `release_notes` length > 5000
- and `should_clip = true`

If `release_notes_link` not provided, [plugin will prompt you](https://github.com/microsoft/fastlane-plugin-appcenter/blob/master/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L83) for a link to full release notes details, and then it will be added in the end of clipped notes text

#### Example:

```ruby
appcenter_upload(
  owner_name: ENV["OWNER"],
  app_name: ENV["APP_AC"],
  ipa: "./build/app.ipa",
  dsym: "./build/app.app.dSYM.zip",
  destinations: "Collaborators",
  notify_testers: false,
  release_notes: sh("cat ./CHANGELOG.md"),
  should_clip: true,
  release_notes_link: "https://github.com/microsoft/fastlane-plugin-appcenter/releases/tag/v1.0.0"
)
```

#### Result:

![image](https://user-images.githubusercontent.com/27571887/58643870-fce37500-82b4-11e9-9cc4-e9f9e86bd34b.png)

**Comment by tonyxiao** [comment]
Got it, so both formats into the changelog itself and. Thanks!
