### ISSUE TITLE
Support some 'dry-run' option

### ISSUE THREAD

**Issue by CAMOBAP** [microsoft/fastlane-plugin-appcenter#85]
On my project, I have a really big Fastfile ~1000, and very often it becomes broken

Recently I did upgrade to 1.0.0 version but unfortunately didn't check API changes...

It will be nice it `appcenter_upload` will support some `dry_run` option which will do as much validation as possible but will not upload artifacts to appcenter

**Comment by derpixeldan** [comment]
@CAMOBAP795 thanks for the feedback. I see the usefulness in your case.

**Comment by jp-andre** [comment]
I can see the usefulness but this is not something we're going to work on. Also, we are trying our best to be fully backwards-compatible within a major version.
