### ISSUE TITLE
Error uploading binary: 500

### ISSUE THREAD

**Issue by jlorfeo** [microsoft/fastlane-plugin-appcenter#89]
Hello everyone,

when I try to upload a binary via fastlane, I get the following error:

Error uploading binary 500: <!DOCTYPE html>
<html lang='en' class="full_height">
  <head>
    <meta charset='utf-8'>
    <title>Server Error</title>
    <meta content="authenticity_token" name="csrf-param" />
    <link href="/assets/application-default.css" media="all" rel="stylesheet" type="text/css" />
    <link href='/favicon.ico' rel='shortcut icon'>
  </head>
  <body class='full_height'>
    <div class='container-fluid full-height full-width'>
      <div class='row-dialog'>
        <div class='centered-vertical'>
          <div class='centered-horizontal'>
            <div class='well'>
              <h3>Ooops…</h3>
              <p class="pad-top">
                We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly. If you want to provide more information, please file a support ticket.
              </p>
              <p>
                <a href="/" class="btn btn-ha-primary">Home</a>
                <a href="mailto:support@hockeyapp.net" class="btn">Support</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class='clear'></div>
    </div>
    <script src="/assets/application-default.js" type="text/javascript"></script>
  </body>
</html>

My build is still labeled as success though.
Is this App Center related?

**Comment by m3nux** [comment]
I have same problem :(

**Comment by setoff** [comment]
https://status.appcenter.ms
> Identified - We have to perform an unplanned maintenance on the Distribute service with a potential downtime of one hour. As a consequence some APIs including uploading, downloading and retrieving releases information won't work. 

It is related to service itself not a plugin.
But anyway plugin's fault that it is completed successfully when `appcenter_upload` catch HTTP errors (I've seen 500, 503 during this shutdown). Swallowing errors is bad especially when using fastlane on CI.

**Comment by derpixeldan** [comment]
Yes, we've had an unplanned maintenance. Let's see the good in this, the error handling in case of service unavailability needs to be improved and abort with a respective error. Thanks for identifying and reporting.

**Comment by bvisin** [comment]
Seeing the same issue.  Any ETA when it will be resolved?

**Comment by jlorfeo** [comment]
„[Status] Identified: We're currently running a migration that will fix the issue, however, it takes a few more hours until it's done. Again, we apologize for the trouble this might have caused“

**Comment by madnotdead** [comment]
Any news related to this? I'm getting the following message 
`[18:26:20]: Binary uploaded`
`[18:26:28]: Error 500: {"code"=>"internal_server_error", "message"=>"internal error (Support ID: b51f665a-2cb8-4b59-8ef0-fcdb0503431a)"}`
`[18:26:28]: Starting dSYM upload...`

**Comment by DennisPan** [comment]
@madnotdead Your error is unrelated to the maintenance mentioned above, which was resolved at Jun 20, 02:03 UTC. I looked up your error and found timeouts happened in backend. It could be transient, so I would suggest give it another try. If it persists, I would suggest reach out to App Center support (from the appcenter.ms), who will be able to dig into more details.

**Comment by madnotdead** [comment]
@DennisPan Thanks, I'll give it a try again.

**Comment by DennisPan** [comment]
Closing this for now. If you hit another 500, feel free to create a new one or re-open this. However, most of the time those are issues with App Center, but the plugin, in which case reaching out to App Center support is another option
