### ISSUE TITLE
Upload to organisation

### ISSUE THREAD

**Issue by mars3142** [microsoft/fastlane-plugin-appcenter#92]
It's not possible to upload apps for organisation. The issue #46 is closed and the PR #75 isn't merged yet. The attached fork is also not working, but because we need to switch from Hockey to AppCenter, the feature is very important for the plugin.

**Comment by DennisPan** [comment]
@mars3142 Looking at the code, my understanding is uploading to organization should be supported already. What's not supported is automatically create an app under an organization. But I assume that's not a blocker for you. 

I'm trying to get this clarified in Issue #46 . Once we have that answered, we can look into next step.

**Comment by DennisPan** [comment]
@mars3142 Based on [this](https://github.com/microsoft/fastlane-plugin-appcenter/issues/46#issuecomment-509279146), uploading to organization is already supported. What's not supported is automatically creating apps under organization. Is that what you are looking for?

**Comment by mars3142** [comment]
@DennisPan Oh, it was my mistake. I just tested it again and my app name has whitespaces and I didn't used - for that. Now it's working fine. Thanks for checking it.
